<?php

namespace Database\Seeders;

use App\Models\DiveSite;
use Illuminate\Database\Seeder;

class CepDiveSiteSeeder extends Seeder
{
    public function run(): void
    {
        $sites = [
            [
                'name' => 'Lac de la Haute-Sûre — Bavignes (Base Nautique)',
                'country' => 'Luxembourg',
                'region' => 'Esch-sur-Sûre',
                'latitude' => 49.9115,
                'longitude' => 5.9080,
                'max_depth' => 18,
                'water_type' => 'lake',
                'conditions' => 'Freshwater lake, visibility 2-5m depending on season. Thermocline around 8-10m in summer. Alternative entry point to the usual Lultzhausen/Insenborn — requires driving around the lake.',
                'marine_life' => 'Pike, perch, carp, trout. Crayfish on rocky bottom.',
                'access_notes' => 'Base nautique de Bavignes, drive around the lake from Lultzhausen. Parking at the nautical base. Nice change of scenery from the usual spots.',
                'facilities' => 'Nautical base with toilets, changing area. Kayak/paddleboard rental nearby.',
                'website_url' => 'https://www.naturpark-sure.lu',
            ],
            [
                'name' => 'Port Fréjus Plongée',
                'country' => 'France',
                'region' => 'Var, Côte d\'Azur',
                'latitude' => 43.4230,
                'longitude' => 6.7370,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 10-30m. Water temp 14-25°C. Boat dives to wrecks and reefs off Fréjus/Saint-Raphaël. Dive center right at the port — 4m from the boats.',
                'marine_life' => 'Groupers, moray eels, octopus, barracuda, scorpionfish. Posidonia meadows. Wrecks with rich encrustation.',
                'access_notes' => 'Aire de carénage, Port Fréjus Est, 83600 Fréjus. Boats La Palanquée (20 divers) and Le Kapor (14 divers).',
                'facilities' => 'Full dive center with rental, fills, courses. FFESSM & PADI.',
                'website_url' => 'https://cip-frejus.com',
            ],
            [
                'name' => 'Easy Dive — Juan-les-Pins',
                'country' => 'France',
                'region' => 'Alpes-Maritimes, Côte d\'Azur',
                'latitude' => 43.5667,
                'longitude' => 7.1083,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 10-30m. Water temp 14-26°C. Boat dives to reefs, walls and wrecks off Antibes/Cap d\'Antibes.',
                'marine_life' => 'Groupers, moray eels, octopus, nudibranchs, gorgonians. Rocky reef formations.',
                'access_notes' => 'Port Gallice, Juan-les-Pins, 06160 Antibes. Open year-round, up to 4 dives/day in high season.',
                'facilities' => 'Full dive center, equipment rental, Aqualung partner. FFESSM & PADI courses from beginner to instructor.',
                'website_url' => 'https://www.easydive.fr',
            ],
            [
                'name' => 'Easy Dive — Cannes',
                'country' => 'France',
                'region' => 'Alpes-Maritimes, Côte d\'Azur',
                'latitude' => 43.5510,
                'longitude' => 7.0140,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 10-30m. Water temp 14-26°C. Boat dives from the old port of Cannes. Sites around Îles de Lérins.',
                'marine_life' => 'Groupers, barracuda, octopus, gorgonians, Posidonia meadows around Lérins islands.',
                'access_notes' => '2 rue Esprit Violet, 06400 Cannes. Old port, platform St Pierre. Parking nearby.',
                'facilities' => 'PADI IDC 5* center, FFESSM affiliated. Full rental, courses beginner to instructor.',
                'website_url' => 'https://www.easydive.fr',
            ],
            [
                'name' => 'Coron Bay',
                'country' => 'Philippines',
                'region' => 'Palawan, Calamian Islands',
                'latitude' => 11.9980,
                'longitude' => 120.2040,
                'max_depth' => 43,
                'water_type' => 'sea',
                'conditions' => 'Tropical. Visibility 5-20m (varies by wreck site). Water temp 26-30°C year-round. Famous WWII Japanese shipwreck graveyard — 12+ wrecks at 10-43m depth.',
                'marine_life' => 'Hard coral encrusted wrecks, lionfish, batfish, nudibranchs, barracuda schools. Dugong sightings at nearby reefs.',
                'access_notes' => '170 nautical miles SW of Manila. Fly to Busuanga (USU) airport, then 30min to Coron Town. Boat dives to wreck sites.',
                'facilities' => 'Multiple dive centers in Coron Town. Nitrox available. Liveaboard options.',
                'nearest_hospital' => 'Coron District Hospital',
                'website_url' => 'https://www.divingsquad.com/philippines-diving/palawan/coron/',
            ],
            [
                'name' => 'Nosy Be',
                'country' => 'Madagascar',
                'region' => 'Diana Region',
                'latitude' => -13.4012,
                'longitude' => 48.2718,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Indian Ocean / Mozambique Channel. Visibility 15-30m. Water temp 24-30°C. Best diving May-November (dry season). Strong currents possible.',
                'marine_life' => 'Whale sharks (Oct-Dec), manta rays, turtles, reef sharks, humpback whales (Jul-Sep). Pristine coral reefs around Nosy Tanikely marine reserve.',
                'access_notes' => 'Fly to Fascene Airport (NOS) via Antananarivo. Dive centers at Ambatoloaka and Hell-Ville. Nearby islands: Nosy Komba, Nosy Mitsio, Nosy Sakatia, Nosy Tanikely.',
                'facilities' => 'Several dive centers, equipment rental, Nitrox. Liveaboard options to Mitsio archipelago.',
                'website_url' => 'https://nosybe.dune-world.com',
            ],
            [
                'name' => 'L\'Estartit — Illes Medes',
                'country' => 'Spain',
                'region' => 'Costa Brava, Catalonia',
                'latitude' => 42.0501,
                'longitude' => 3.1962,
                'max_depth' => 50,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean marine reserve. Visibility 10-25m. Water temp 13-24°C. 10 buoyed dive sites around the 7 Medes Islands. Protected since 1983 — exceptional marine life density.',
                'marine_life' => 'Huge groupers (unafraid of divers), moray eels, eagle rays, barracuda, octopus, red coral, gorgonians. Dolphin Cave — cathedral-like chamber with light beams.',
                'access_notes' => 'L\'Estartit, Girona. AP-7 exit 6 (from Barcelona) or exit 3 (from France). Islands 1km offshore, 10min by boat.',
                'facilities' => 'Multiple dive centers in town. Marine park entry fee required.',
                'website_url' => 'https://www.padi.com/diving-in/spain/l-estartit/',
            ],
            [
                'name' => 'El Rey del Mar — L\'Estartit',
                'country' => 'Spain',
                'region' => 'Costa Brava, Catalonia',
                'latitude' => 42.0501,
                'longitude' => 3.1962,
                'max_depth' => 50,
                'water_type' => 'sea',
                'conditions' => 'Dive center inside Hotel Panorama, 50m from the beach. Boat dives to Medes Islands and Montgrí coast within the Natural Park.',
                'marine_life' => 'Groupers, moray eels, octopus, red coral, gorgonians, nudibranchs. Posidonia meadows on the coast.',
                'access_notes' => 'Hotel Panorama, Av. Grècia 5, 17258 L\'Estartit. GPS: 42.05012, 3.19622.',
                'facilities' => 'SSI & PADI courses, full rental, readaptation dives on Montgrí coast before reserve dives.',
                'website_url' => 'https://www.elreidelmar.com',
            ],
            [
                'name' => 'La Sirena Diving Center — L\'Estartit',
                'country' => 'Spain',
                'region' => 'Costa Brava, Catalonia',
                'latitude' => 42.0490,
                'longitude' => 3.1950,
                'max_depth' => 50,
                'water_type' => 'sea',
                'conditions' => 'Dive center in L\'Estartit. Boat dives to Medes Islands marine reserve — 7 islands including Meda Gran, Meda Petita, Carall Bernat.',
                'marine_life' => 'Groupers, moray eels, eagle rays, barracuda, octopus, red coral, gorgonians. Dolphin Cave on Meda Petita.',
                'access_notes' => 'L\'Estartit, Costa Brava. Approximately 1 mile from town to the islands.',
                'facilities' => 'Courses from beginner to professional, snorkeling trips, full rental.',
                'website_url' => 'https://divingcenterlasirena.com',
            ],
            [
                'name' => 'Safaga',
                'country' => 'Egypt',
                'region' => 'Red Sea',
                'latitude' => 26.7654,
                'longitude' => 33.9448,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Red Sea. Visibility 20-40m. Water temp 22-30°C. Less crowded than Hurghada. Famous for Salem Express wreck (30m), Panorama Reef, Tobia Arbaa. Strong currents on some sites.',
                'marine_life' => 'Dolphins, turtles, reef sharks, manta rays, huge gorgonian fans, soft corals. Salem Express wreck teeming with life.',
                'access_notes' => '60km south of Hurghada airport. Multiple dive centers and resorts along the coast.',
                'facilities' => 'Dive centers, Nitrox, liveaboard departures. Day trips to offshore reefs.',
                'nearest_hospital' => 'Safaga General Hospital',
                'website_url' => 'https://redsea.dune-world.com',
            ],
            [
                'name' => 'Sesimbra',
                'country' => 'Portugal',
                'region' => 'Setúbal, Lisbon Region',
                'latitude' => 38.4445,
                'longitude' => -9.1015,
                'max_depth' => 35,
                'water_type' => 'sea',
                'conditions' => 'Atlantic. Visibility 5-15m. Water temp 14-20°C. Wrecks and reefs off Arrábida Natural Park. Famous River Gurara wreck (Nigerian cargo ship, sunk 1989). Cold water — thick wetsuit or drysuit recommended.',
                'marine_life' => 'Octopus, conger eels, nudibranchs, seahorses, sunfish (Mola mola in season), schools of bream and bass.',
                'access_notes' => '40km south of Lisbon. Dive centers at Porto de Abrigo de Sesimbra. Boat dives.',
                'facilities' => 'Several dive centers, equipment rental, courses. Arrábida marine park.',
                'website_url' => 'https://scubago.com/europe/portugal/lisbon-region/setubal/sesimbra',
            ],
            [
                'name' => 'Peniche — Berlengas',
                'country' => 'Portugal',
                'region' => 'Leiria, Centro',
                'latitude' => 39.3558,
                'longitude' => -9.3811,
                'max_depth' => 30,
                'water_type' => 'sea',
                'conditions' => 'Atlantic. Visibility 5-20m. Water temp 14-19°C. Berlenga Grande island 30min by boat — marine reserve with caves, tunnels, arches. Exposed to Atlantic swell — weather dependent.',
                'marine_life' => 'Lobsters, octopus, conger eels, nudibranchs, wrasse, bream. Kelp forests. Occasional sunfish and dolphins.',
                'access_notes' => 'Peniche, 90km north of Lisbon. Dive centers at the fishing port. Boat to Berlengas. Camping and restaurant on the island.',
                'facilities' => 'Dive centers with boat access, equipment rental, courses.',
                'website_url' => 'https://www.padi.com/diving-in/portugal/peniche/',
            ],
            // ── Batch 2 ──────────────────────────────────────────
            [
                'name' => 'Brother Islands',
                'country' => 'Egypt',
                'region' => 'Red Sea',
                'latitude' => 26.3200,
                'longitude' => 34.8500,
                'max_depth' => 80,
                'water_type' => 'sea',
                'conditions' => 'Red Sea offshore. Visibility 20-40m. Water temp 22-28°C. Two tiny islands (Big & Little Brother) — exposed tips of massive reef pillars from abyssal depths. Liveaboard only, 200km south of Ras Mohammed. Strong currents, advanced divers.',
                'marine_life' => 'Oceanic whitetip sharks, hammerheads, thresher sharks, grey reef sharks, manta rays. Aida wreck on Big Brother (30-80m). Pristine soft coral walls.',
                'access_notes' => 'Liveaboard from Hurghada or Marsa Alam. No shore access. Weather dependent.',
                'facilities' => 'Liveaboard only. Mooring buoys.',
            ],
            [
                'name' => 'Curaçao',
                'country' => 'Curaçao',
                'region' => 'Caribbean, ABC Islands',
                'latitude' => 12.1696,
                'longitude' => -68.9900,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Caribbean. Visibility 20-40m. Water temp 26-29°C year-round. Shore diving paradise — 65+ dive sites accessible from shore. Gentle currents, calm conditions. Reef drops off steeply from shore.',
                'marine_life' => 'Turtles, seahorses, frogfish, octopus, moray eels, tarpon, barracuda. Pristine coral reefs, sponge gardens. Mushroom Forest famous site.',
                'access_notes' => 'Fly to Hato Airport (CUR). Dive sites all along the leeward coast. Easy shore entry at most sites.',
                'facilities' => 'Many dive centers, shore diving with truck/tank service, Nitrox widely available.',
            ],
            [
                'name' => 'Cocos Island (Isla del Coco)',
                'country' => 'Costa Rica',
                'region' => 'Pacific Ocean',
                'latitude' => 5.5168,
                'longitude' => -87.0697,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Open Pacific. Visibility 10-30m. Water temp 24-30°C. UNESCO World Heritage. 550km offshore — liveaboard only (36h crossing). ~20 dive sites around the island. Strong currents, advanced divers. Thermoclines.',
                'marine_life' => 'Schooling scalloped hammerheads (hundreds), whale sharks, manta rays, dolphins, Galápagos sharks, marble rays, whitetip reef sharks. Bajo Alcyone seamount at 27m.',
                'access_notes' => 'Liveaboard from Puntarenas, Costa Rica. 36-hour crossing each way. Trips typically 10 days.',
                'facilities' => 'Liveaboard only. National park — no facilities on island.',
            ],
            [
                'name' => 'Mega Dive — Sesimbra',
                'country' => 'Portugal',
                'region' => 'Setúbal, Lisbon Region',
                'latitude' => 38.4440,
                'longitude' => -9.1020,
                'max_depth' => 35,
                'water_type' => 'sea',
                'conditions' => 'Atlantic. Dive center at Porto de Abrigo de Sesimbra, integrated in Parque Marinho Prof. Luiz Saldanha. Boat dives to Arrábida marine reserve.',
                'marine_life' => 'Octopus, conger eels, nudibranchs, seahorses, sunfish (Mola mola). Wreck of River Gurara.',
                'access_notes' => 'Av. dos Náufragos, Armazém 2 e 3, Bloco D, 2970-152 Sesimbra.',
                'facilities' => 'Dive school, nautical events, equipment rental, courses. Kayaking and dolphin watching also available.',
                'website_url' => 'https://www.megadive.pt',
            ],
            [
                'name' => 'Port-Cros',
                'country' => 'France',
                'region' => 'Var, Côte d\'Azur',
                'latitude' => 43.0044,
                'longitude' => 6.3936,
                'max_depth' => 45,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 15-30m. Water temp 14-25°C. National marine park since 1963 — oldest in Europe. Protected waters with exceptional biodiversity. Grouper reserve.',
                'marine_life' => 'Large groupers (protected, very approachable), barracuda, moray eels, eagle rays, dentex. Posidonia meadows, gorgonians, red coral. La Gabinière — world-class wall dive.',
                'access_notes' => 'Boat from Hyères, Le Lavandou, or Bormes-les-Mimosas. ~20min crossing. Dive permit required from park authority.',
                'facilities' => 'Dive centers on the mainland. Limited facilities on the island. Marine park regulations apply.',
            ],
            [
                'name' => 'Cape Verde (Sal)',
                'country' => 'Cape Verde',
                'region' => 'Sal Island, Atlantic',
                'latitude' => 16.7260,
                'longitude' => -22.9340,
                'max_depth' => 35,
                'water_type' => 'sea',
                'conditions' => 'Atlantic/tropical. Visibility 15-30m. Water temp 22-27°C. Volcanic underwater landscapes, caves, arches, tunnels. Mild currents on most sites.',
                'marine_life' => 'Nurse sharks, lemon sharks, manta rays, turtles, moray eels, whale sharks (seasonal). Volcanic rock formations with rich marine life.',
                'access_notes' => 'Fly to Sal (SID) or Boa Vista. Dive centers in Santa Maria (Sal).',
                'facilities' => 'Several dive centers, equipment rental, courses. Nitrox available.',
            ],
            [
                'name' => 'Silfra Fissure',
                'country' => 'Iceland',
                'region' => 'Þingvellir National Park',
                'latitude' => 64.2558,
                'longitude' => -21.1164,
                'max_depth' => 18,
                'water_type' => 'freshwater',
                'conditions' => 'Glacial spring water. Visibility 80-100m+ (clearest water on Earth). Water temp 2-4°C year-round. Drysuit mandatory. Dive between the North American and Eurasian tectonic plates — only place in the world.',
                'marine_life' => 'Minimal — bright green algae (troll hair), some Arctic char. The attraction is the geology and visibility, not marine life.',
                'access_notes' => 'Þingvellir National Park, 60km from Reykjavik. Silfra car park. Drysuit certification required.',
                'facilities' => 'Dive operators provide all equipment. Changing facilities at car park. No fills on site.',
            ],
            [
                'name' => 'Guadeloupe — Réserve Cousteau',
                'country' => 'France',
                'region' => 'Guadeloupe, Caribbean',
                'latitude' => 16.1670,
                'longitude' => -61.7890,
                'max_depth' => 30,
                'water_type' => 'sea',
                'conditions' => 'Caribbean. Visibility 15-30m. Water temp 26-29°C. Réserve Cousteau off Pigeon Island (Bouillante) — named after Jacques Cousteau who filmed here. Protected marine area.',
                'marine_life' => 'Turtles, seahorses, barracuda, parrotfish, angelfish, lobsters. Coral gardens, sponges. Occasional dolphins and rays.',
                'access_notes' => 'Fly to Pointe-à-Pitre (PTP). Dive centers in Bouillante and Malendure beach. Boat to Pigeon Island in 5min.',
                'facilities' => 'Multiple dive centers, equipment rental, courses. Glass-bottom boats for non-divers.',
            ],
            [
                'name' => 'Martinique',
                'country' => 'France',
                'region' => 'Martinique, Caribbean',
                'latitude' => 14.6415,
                'longitude' => -61.0242,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Caribbean. Visibility 15-30m. Water temp 26-29°C. Volcanic underwater landscapes. Famous for the 1902 eruption wrecks in Saint-Pierre bay — 14 ships sunk by pyroclastic flow from Mont Pelée.',
                'marine_life' => 'Turtles, seahorses, frogfish, barracuda, nurse sharks. Coral-encrusted wrecks. Diamond Rock — dramatic volcanic pinnacle.',
                'access_notes' => 'Fly to Fort-de-France (FDF). Dive centers in Saint-Pierre, Les Anses-d\'Arlet, Le Diamant.',
                'facilities' => 'Multiple dive centers, equipment rental, courses. Wreck diving specialty.',
            ],
            [
                'name' => 'Extra Divers — Jebel Sifah, Oman',
                'country' => 'Oman',
                'region' => 'Muscat Governorate',
                'latitude' => 23.4800,
                'longitude' => 58.7300,
                'max_depth' => 30,
                'water_type' => 'sea',
                'conditions' => 'Gulf of Oman. Visibility 5-20m (variable). Water temp 22-32°C. Whale sharks Jul-Nov. Munassir wreck, Fahal Islands, Ras Abu Daoud reefs. German-managed center.',
                'marine_life' => 'Whale sharks (seasonal), turtles, cuttlefish, nudibranchs, schools of jacks and barracuda. Reef sharks, eagle rays.',
                'access_notes' => 'Sifawy Boutique Resort, Jebel Sifah, <1h from Muscat. 2-tank boat dives departing 9am.',
                'facilities' => 'Full dive center by Extra Divers Worldwide. Equipment rental, Nitrox, courses.',
                'website_url' => 'https://sifawyhotel.com/extra-divers-dive-centre-at-jebel-sifah/',
            ],
            [
                'name' => 'OK Maldives (Liveaboard)',
                'country' => 'Maldives',
                'region' => 'Indian Ocean',
                'latitude' => 4.1755,
                'longitude' => 73.5093,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Indian Ocean. Visibility 15-40m. Water temp 27-30°C year-round. 26 atolls, channel dives with current. Best Jan-Apr (NE monsoon, mantas) and Aug-Nov (SW monsoon, whale sharks).',
                'marine_life' => 'Manta rays, whale sharks, hammerheads, grey reef sharks, eagle rays, turtles, dolphins. Pristine coral reefs in channels (kandus).',
                'access_notes' => 'Fly to Malé (MLE). Liveaboard departures from Malé harbor. Typical 7-10 day itineraries.',
                'facilities' => 'Liveaboard with full dive deck, Nitrox, equipment rental.',
            ],
            [
                'name' => 'Les Amis des Maldives (Liveaboard)',
                'country' => 'Maldives',
                'region' => 'Indian Ocean',
                'latitude' => 4.1755,
                'longitude' => 73.5093,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Diving cruise operator. Ocean One vessel (37m × 12m, 3 decks). Up to 3 dives/day on the best spots of each atoll. PADI & CMAS training available on board.',
                'marine_life' => 'Grey & whitetip sharks, eagle rays, mantas, whale sharks, dolphins, turtles, napoleons. Ocean passes and drop-offs.',
                'access_notes' => 'Depart from Malé. Cruises across multiple atolls (north and south itineraries).',
                'facilities' => 'Liveaboard with jacuzzi, spacious decks, en-suite cabins. PADI OW/AOW, CMAS PE40/N2, Nitrox training.',
                'website_url' => 'https://www.amisdesmaldives.com',
            ],
            [
                'name' => 'L\'Océanos (Liveaboard Égypte)',
                'country' => 'Egypt',
                'region' => 'Red Sea',
                'latitude' => 27.1780,
                'longitude' => 33.8414,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Red Sea liveaboard. M/Y Oceanos (39m), 13 cabins for 26 divers. Safari routes: Brothers, Daedalus, Elphinstone, Fury Shoals, St. John\'s.',
                'marine_life' => 'Sharks (oceanic whitetip, hammerhead, grey reef), dolphins, mantas, turtles. Pristine coral walls, wrecks.',
                'access_notes' => 'Departs from Hurghada. Typical 7-day safari routes.',
                'facilities' => 'Full dive deck, Nitrox, equipment rental, en-suite cabins with A/C.',
            ],
            [
                'name' => 'Carrière de Rochefontaine',
                'country' => 'Belgium',
                'region' => 'Namur, Wallonia',
                'latitude' => 50.2700,
                'longitude' => 4.6200,
                'max_depth' => 35,
                'water_type' => 'quarry',
                'conditions' => 'Flooded quarry. Visibility 3-8m. Water temp 4-18°C. Platforms at various depths. Training site for Belgian clubs.',
                'marine_life' => 'Pike, perch, carp, trout. Crayfish.',
                'access_notes' => 'Rochefontaine, Namur province. Club access — check opening schedule.',
                'facilities' => 'Changing rooms, parking, fill station nearby.',
            ],
            [
                'name' => 'Carrière de Villers-deux-Églises',
                'country' => 'Belgium',
                'region' => 'Namur, Wallonia',
                'latitude' => 50.2100,
                'longitude' => 4.5600,
                'max_depth' => 20,
                'water_type' => 'quarry',
                'conditions' => 'Flooded quarry. Visibility 3-6m. Water temp 4-18°C. Popular training site for Belgian and Luxembourg clubs.',
                'marine_life' => 'Pike, perch, carp.',
                'access_notes' => 'Villers-deux-Églises, Namur province. Club access.',
                'facilities' => 'Basic facilities, parking.',
            ],
            [
                'name' => 'Remerschen — Baggerweieren',
                'country' => 'Luxembourg',
                'region' => 'Moselle, Schengen',
                'latitude' => 49.4950,
                'longitude' => 6.3580,
                'max_depth' => 8,
                'water_type' => 'lake',
                'conditions' => 'Former gravel pit lakes. Visibility 2-5m. Water temp 10-24°C. Shallow — good for training and try-dives. Swimming area with entry fee (€6 adults). Algae blooms possible in summer.',
                'marine_life' => 'Carp, pike, perch. Freshwater mussels.',
                'access_notes' => 'Remerschen, near Schengen. 25ha site with beaches, parking. Entry fee applies.',
                'facilities' => 'Toilets, changing areas, beach volleyball, playground. Restaurant nearby.',
                'website_url' => 'https://www.visitluxembourg.com/place/remerschen-lakes',
            ],
            // ── Batch 3 ──────────────────────────────────────────
            [
                'name' => 'Orca Diving — Ustica',
                'country' => 'Italy',
                'region' => 'Sicily, Tyrrhenian Sea',
                'latitude' => 38.7108,
                'longitude' => 13.1800,
                'max_depth' => 50,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 20-40m. Water temp 15-27°C. Marine Protected Area — Italy\'s first (1986). Volcanic island 67km NW of Palermo. Walls, caves, shoals. Colombara Shoal, Secca d\'Africa, Punta San Paolo.',
                'marine_life' => 'Groupers, barracuda, amberjack, moray eels, octopus. Orange Astroides coral, gorgonians. Occasional dolphins, tuna.',
                'access_notes' => 'Ferry/hydrofoil from Palermo (~1h30). Dive center at the harbour, walking distance from accommodation.',
                'facilities' => 'PADI dive center, equipment rental, boats to all sites in minutes. Courses from baptism to advanced.',
                'website_url' => 'https://www.orcadivingustica.com',
            ],
            [
                'name' => 'L\'Incantu — Galéria',
                'country' => 'France',
                'region' => 'Haute-Corse, Corsica',
                'latitude' => 42.4200,
                'longitude' => 8.6400,
                'max_depth' => 60,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 15-30m. Water temp 14-25°C. Gateway to Réserve Naturelle de Scandola (UNESCO). Largest dive center in Corsica — 6 boats, ~25,000 dives/year. FFESSM, PADI, CMAS approved.',
                'marine_life' => 'Groupers, dentex, barracuda, moray eels, lobsters. Red coral, gorgonians. Scandola\'s protected waters teem with life.',
                'access_notes' => 'Galéria, Haute-Corse. Residence with apartments, heated pool, restaurant. Meet at 8:30 and 14:30 for dive trips.',
                'facilities' => 'Full dive center, equipment rental, courses up to N4/Dive Guide. Accommodation + diving packages.',
                'website_url' => 'https://www.incantu.com',
            ],
            [
                'name' => 'Dive4Life — Siegburg',
                'country' => 'Germany',
                'region' => 'North Rhine-Westphalia',
                'latitude' => 50.7930,
                'longitude' => 7.2030,
                'max_depth' => 20,
                'water_type' => 'pool',
                'conditions' => 'Indoor diving tower. 3 million litres crystal-clear heated water at 26°C. 20m deep, 10m diameter. Maya-themed décor with caves, grottos, and a wreck. Year-round perfect conditions. Germany\'s largest heated indoor diving center.',
                'marine_life' => 'None — indoor facility.',
                'access_notes' => 'Siegburg, near Bonn. Easy access from A3/A560. Parking on site.',
                'facilities' => 'Full dive center, equipment rental, courses, restaurant, hotel partnership (Stay & Dive packages). Events and Nitrox.',
                'website_url' => 'https://www.dive4life.de',
            ],
            [
                'name' => 'Boschmolenplas — Heel',
                'country' => 'Netherlands',
                'region' => 'Limburg',
                'latitude' => 51.1800,
                'longitude' => 5.9000,
                'max_depth' => 28,
                'water_type' => 'lake',
                'conditions' => 'Freshwater lake. Visibility up to 12m (excellent for NL). Privately run dive site with submerged artificial objects and attractions. Rich underwater flora and fauna.',
                'marine_life' => 'Pike, perch, carp, crayfish. Abundant aquatic plants.',
                'access_notes' => 'Heel, Limburg province (south Netherlands). Private site — check opening hours and entry requirements.',
                'facilities' => 'Parking, entry facilities. Privately managed.',
            ],
        ];

        foreach ($sites as $site) {
            DiveSite::updateOrCreate(
                ['name' => $site['name']],
                array_merge($site, ['is_active' => true]),
            );
        }
    }
}
