<?php

namespace Database\Seeders;

use App\Models\DiveSite;
use Illuminate\Database\Seeder;

class CepDiveSiteSeeder extends Seeder
{
    public function run(): void
    {
        $sites = [
            [
                'name' => 'Lac de la Haute-Sûre — Bavignes (Base Nautique)',
                'country' => 'Luxembourg',
                'region' => 'Esch-sur-Sûre',
                'latitude' => 49.9115,
                'longitude' => 5.9080,
                'max_depth' => 18,
                'water_type' => 'lake',
                'conditions' => 'Freshwater lake, visibility 2-5m depending on season. Thermocline around 8-10m in summer. Alternative entry point to the usual Lultzhausen/Insenborn — requires driving around the lake.',
                'marine_life' => 'Pike, perch, carp, trout. Crayfish on rocky bottom.',
                'access_notes' => 'Base nautique de Bavignes, drive around the lake from Lultzhausen. Parking at the nautical base. Nice change of scenery from the usual spots.',
                'facilities' => 'Nautical base with toilets, changing area. Kayak/paddleboard rental nearby.',
                'website_url' => 'https://www.naturpark-sure.lu',
            ],
            [
                'name' => 'Port Fréjus Plongée',
                'country' => 'France',
                'region' => 'Var, Côte d\'Azur',
                'latitude' => 43.4230,
                'longitude' => 6.7370,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 10-30m. Water temp 14-25°C. Boat dives to wrecks and reefs off Fréjus/Saint-Raphaël. Dive center right at the port — 4m from the boats.',
                'marine_life' => 'Groupers, moray eels, octopus, barracuda, scorpionfish. Posidonia meadows. Wrecks with rich encrustation.',
                'access_notes' => 'Aire de carénage, Port Fréjus Est, 83600 Fréjus. Boats La Palanquée (20 divers) and Le Kapor (14 divers).',
                'facilities' => 'Full dive center with rental, fills, courses. FFESSM & PADI.',
                'website_url' => 'https://cip-frejus.com',
            ],
            [
                'name' => 'Easy Dive — Juan-les-Pins',
                'country' => 'France',
                'region' => 'Alpes-Maritimes, Côte d\'Azur',
                'latitude' => 43.5667,
                'longitude' => 7.1083,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 10-30m. Water temp 14-26°C. Boat dives to reefs, walls and wrecks off Antibes/Cap d\'Antibes.',
                'marine_life' => 'Groupers, moray eels, octopus, nudibranchs, gorgonians. Rocky reef formations.',
                'access_notes' => 'Port Gallice, Juan-les-Pins, 06160 Antibes. Open year-round, up to 4 dives/day in high season.',
                'facilities' => 'Full dive center, equipment rental, Aqualung partner. FFESSM & PADI courses from beginner to instructor.',
                'website_url' => 'https://www.easydive.fr',
            ],
            [
                'name' => 'Easy Dive — Cannes',
                'country' => 'France',
                'region' => 'Alpes-Maritimes, Côte d\'Azur',
                'latitude' => 43.5510,
                'longitude' => 7.0140,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 10-30m. Water temp 14-26°C. Boat dives from the old port of Cannes. Sites around Îles de Lérins.',
                'marine_life' => 'Groupers, barracuda, octopus, gorgonians, Posidonia meadows around Lérins islands.',
                'access_notes' => '2 rue Esprit Violet, 06400 Cannes. Old port, platform St Pierre. Parking nearby.',
                'facilities' => 'PADI IDC 5* center, FFESSM affiliated. Full rental, courses beginner to instructor.',
                'website_url' => 'https://www.easydive.fr',
            ],
            [
                'name' => 'Coron Bay',
                'country' => 'Philippines',
                'region' => 'Palawan, Calamian Islands',
                'latitude' => 11.9980,
                'longitude' => 120.2040,
                'max_depth' => 43,
                'water_type' => 'sea',
                'conditions' => 'Tropical. Visibility 5-20m (varies by wreck site). Water temp 26-30°C year-round. Famous WWII Japanese shipwreck graveyard — 12+ wrecks at 10-43m depth.',
                'marine_life' => 'Hard coral encrusted wrecks, lionfish, batfish, nudibranchs, barracuda schools. Dugong sightings at nearby reefs.',
                'access_notes' => '170 nautical miles SW of Manila. Fly to Busuanga (USU) airport, then 30min to Coron Town. Boat dives to wreck sites.',
                'facilities' => 'Multiple dive centers in Coron Town. Nitrox available. Liveaboard options.',
                'nearest_hospital' => 'Coron District Hospital',
                'website_url' => 'https://www.divingsquad.com/philippines-diving/palawan/coron/',
            ],
            [
                'name' => 'Nosy Be',
                'country' => 'Madagascar',
                'region' => 'Diana Region',
                'latitude' => -13.4012,
                'longitude' => 48.2718,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Indian Ocean / Mozambique Channel. Visibility 15-30m. Water temp 24-30°C. Best diving May-November (dry season). Strong currents possible.',
                'marine_life' => 'Whale sharks (Oct-Dec), manta rays, turtles, reef sharks, humpback whales (Jul-Sep). Pristine coral reefs around Nosy Tanikely marine reserve.',
                'access_notes' => 'Fly to Fascene Airport (NOS) via Antananarivo. Dive centers at Ambatoloaka and Hell-Ville. Nearby islands: Nosy Komba, Nosy Mitsio, Nosy Sakatia, Nosy Tanikely.',
                'facilities' => 'Several dive centers, equipment rental, Nitrox. Liveaboard options to Mitsio archipelago.',
                'website_url' => 'https://nosybe.dune-world.com',
            ],
            [
                'name' => 'L\'Estartit — Illes Medes',
                'country' => 'Spain',
                'region' => 'Costa Brava, Catalonia',
                'latitude' => 42.0501,
                'longitude' => 3.1962,
                'max_depth' => 50,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean marine reserve. Visibility 10-25m. Water temp 13-24°C. 10 buoyed dive sites around the 7 Medes Islands. Protected since 1983 — exceptional marine life density.',
                'marine_life' => 'Huge groupers (unafraid of divers), moray eels, eagle rays, barracuda, octopus, red coral, gorgonians. Dolphin Cave — cathedral-like chamber with light beams.',
                'access_notes' => 'L\'Estartit, Girona. AP-7 exit 6 (from Barcelona) or exit 3 (from France). Islands 1km offshore, 10min by boat.',
                'facilities' => 'Multiple dive centers in town. Marine park entry fee required.',
                'website_url' => 'https://www.padi.com/diving-in/spain/l-estartit/',
            ],
            [
                'name' => 'El Rey del Mar — L\'Estartit',
                'country' => 'Spain',
                'region' => 'Costa Brava, Catalonia',
                'latitude' => 42.0501,
                'longitude' => 3.1962,
                'max_depth' => 50,
                'water_type' => 'sea',
                'conditions' => 'Dive center inside Hotel Panorama, 50m from the beach. Boat dives to Medes Islands and Montgrí coast within the Natural Park.',
                'marine_life' => 'Groupers, moray eels, octopus, red coral, gorgonians, nudibranchs. Posidonia meadows on the coast.',
                'access_notes' => 'Hotel Panorama, Av. Grècia 5, 17258 L\'Estartit. GPS: 42.05012, 3.19622.',
                'facilities' => 'SSI & PADI courses, full rental, readaptation dives on Montgrí coast before reserve dives.',
                'website_url' => 'https://www.elreidelmar.com',
            ],
            [
                'name' => 'La Sirena Diving Center — L\'Estartit',
                'country' => 'Spain',
                'region' => 'Costa Brava, Catalonia',
                'latitude' => 42.0490,
                'longitude' => 3.1950,
                'max_depth' => 50,
                'water_type' => 'sea',
                'conditions' => 'Dive center in L\'Estartit. Boat dives to Medes Islands marine reserve — 7 islands including Meda Gran, Meda Petita, Carall Bernat.',
                'marine_life' => 'Groupers, moray eels, eagle rays, barracuda, octopus, red coral, gorgonians. Dolphin Cave on Meda Petita.',
                'access_notes' => 'L\'Estartit, Costa Brava. Approximately 1 mile from town to the islands.',
                'facilities' => 'Courses from beginner to professional, snorkeling trips, full rental.',
                'website_url' => 'https://divingcenterlasirena.com',
            ],
            [
                'name' => 'Safaga',
                'country' => 'Egypt',
                'region' => 'Red Sea',
                'latitude' => 26.7654,
                'longitude' => 33.9448,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Red Sea. Visibility 20-40m. Water temp 22-30°C. Less crowded than Hurghada. Famous for Salem Express wreck (30m), Panorama Reef, Tobia Arbaa. Strong currents on some sites.',
                'marine_life' => 'Dolphins, turtles, reef sharks, manta rays, huge gorgonian fans, soft corals. Salem Express wreck teeming with life.',
                'access_notes' => '60km south of Hurghada airport. Multiple dive centers and resorts along the coast.',
                'facilities' => 'Dive centers, Nitrox, liveaboard departures. Day trips to offshore reefs.',
                'nearest_hospital' => 'Safaga General Hospital',
                'website_url' => 'https://redsea.dune-world.com',
            ],
            [
                'name' => 'Sesimbra',
                'country' => 'Portugal',
                'region' => 'Setúbal, Lisbon Region',
                'latitude' => 38.4445,
                'longitude' => -9.1015,
                'max_depth' => 35,
                'water_type' => 'sea',
                'conditions' => 'Atlantic. Visibility 5-15m. Water temp 14-20°C. Wrecks and reefs off Arrábida Natural Park. Famous River Gurara wreck (Nigerian cargo ship, sunk 1989). Cold water — thick wetsuit or drysuit recommended.',
                'marine_life' => 'Octopus, conger eels, nudibranchs, seahorses, sunfish (Mola mola in season), schools of bream and bass.',
                'access_notes' => '40km south of Lisbon. Dive centers at Porto de Abrigo de Sesimbra. Boat dives.',
                'facilities' => 'Several dive centers, equipment rental, courses. Arrábida marine park.',
                'website_url' => 'https://scubago.com/europe/portugal/lisbon-region/setubal/sesimbra',
            ],
            [
                'name' => 'Peniche — Berlengas',
                'country' => 'Portugal',
                'region' => 'Leiria, Centro',
                'latitude' => 39.3558,
                'longitude' => -9.3811,
                'max_depth' => 30,
                'water_type' => 'sea',
                'conditions' => 'Atlantic. Visibility 5-20m. Water temp 14-19°C. Berlenga Grande island 30min by boat — marine reserve with caves, tunnels, arches. Exposed to Atlantic swell — weather dependent.',
                'marine_life' => 'Lobsters, octopus, conger eels, nudibranchs, wrasse, bream. Kelp forests. Occasional sunfish and dolphins.',
                'access_notes' => 'Peniche, 90km north of Lisbon. Dive centers at the fishing port. Boat to Berlengas. Camping and restaurant on the island.',
                'facilities' => 'Dive centers with boat access, equipment rental, courses.',
                'website_url' => 'https://www.padi.com/diving-in/portugal/peniche/',
            ],
        ];

        foreach ($sites as $site) {
            DiveSite::updateOrCreate(
                ['name' => $site['name']],
                array_merge($site, ['is_active' => true]),
            );
        }
    }
}
