<?php

namespace Database\Seeders;

use App\Models\DiveSite;
use Illuminate\Database\Seeder;

class CepDiveSiteSeeder extends Seeder
{
    public function run(): void
    {
        $sites = [
            [
                'name' => 'Lac de la Haute-Sûre — Bavignes (Base Nautique)',
                'country' => 'Luxembourg',
                'region' => 'Esch-sur-Sûre',
                'latitude' => 49.9115,
                'longitude' => 5.9080,
                'max_depth' => 18,
                'water_type' => 'lake',
                'conditions' => 'Freshwater lake, visibility 2-5m depending on season. Thermocline around 8-10m in summer. Alternative entry point to the usual Lultzhausen/Insenborn — requires driving around the lake.',
                'marine_life' => 'Pike, perch, carp, trout. Crayfish on rocky bottom.',
                'access_notes' => 'Base nautique de Bavignes, drive around the lake from Lultzhausen. Parking at the nautical base. Nice change of scenery from the usual spots.',
                'facilities' => 'Nautical base with toilets, changing area. Kayak/paddleboard rental nearby.',
                'website_url' => 'https://www.naturpark-sure.lu',
            ],
            [
                'name' => 'Port Fréjus Plongée',
                'country' => 'France',
                'region' => 'Var, Côte d\'Azur',
                'latitude' => 43.4230,
                'longitude' => 6.7370,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 10-30m. Water temp 14-25°C. Boat dives to wrecks and reefs off Fréjus/Saint-Raphaël. Dive center right at the port — 4m from the boats.',
                'marine_life' => 'Groupers, moray eels, octopus, barracuda, scorpionfish. Posidonia meadows. Wrecks with rich encrustation.',
                'access_notes' => 'Aire de carénage, Port Fréjus Est, 83600 Fréjus. Boats La Palanquée (20 divers) and Le Kapor (14 divers).',
                'facilities' => 'Full dive center with rental, fills, courses. FFESSM & PADI.',
                'website_url' => 'https://cip-frejus.com',
            ],
            [
                'name' => 'Easy Dive — Juan-les-Pins',
                'country' => 'France',
                'region' => 'Alpes-Maritimes, Côte d\'Azur',
                'latitude' => 43.5667,
                'longitude' => 7.1083,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 10-30m. Water temp 14-26°C. Boat dives to reefs, walls and wrecks off Antibes/Cap d\'Antibes.',
                'marine_life' => 'Groupers, moray eels, octopus, nudibranchs, gorgonians. Rocky reef formations.',
                'access_notes' => 'Port Gallice, Juan-les-Pins, 06160 Antibes. Open year-round, up to 4 dives/day in high season.',
                'facilities' => 'Full dive center, equipment rental, Aqualung partner. FFESSM & PADI courses from beginner to instructor.',
                'website_url' => 'https://www.easydive.fr',
            ],
            [
                'name' => 'Easy Dive — Cannes',
                'country' => 'France',
                'region' => 'Alpes-Maritimes, Côte d\'Azur',
                'latitude' => 43.5510,
                'longitude' => 7.0140,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 10-30m. Water temp 14-26°C. Boat dives from the old port of Cannes. Sites around Îles de Lérins.',
                'marine_life' => 'Groupers, barracuda, octopus, gorgonians, Posidonia meadows around Lérins islands.',
                'access_notes' => '2 rue Esprit Violet, 06400 Cannes. Old port, platform St Pierre. Parking nearby.',
                'facilities' => 'PADI IDC 5* center, FFESSM affiliated. Full rental, courses beginner to instructor.',
                'website_url' => 'https://www.easydive.fr',
            ],
            [
                'name' => 'Coron Bay',
                'country' => 'Philippines',
                'region' => 'Palawan, Calamian Islands',
                'latitude' => 11.9980,
                'longitude' => 120.2040,
                'max_depth' => 43,
                'water_type' => 'sea',
                'conditions' => 'Tropical. Visibility 5-20m (varies by wreck site). Water temp 26-30°C year-round. Famous WWII Japanese shipwreck graveyard — 12+ wrecks at 10-43m depth.',
                'marine_life' => 'Hard coral encrusted wrecks, lionfish, batfish, nudibranchs, barracuda schools. Dugong sightings at nearby reefs.',
                'access_notes' => '170 nautical miles SW of Manila. Fly to Busuanga (USU) airport, then 30min to Coron Town. Boat dives to wreck sites.',
                'facilities' => 'Multiple dive centers in Coron Town. Nitrox available. Liveaboard options.',
                'nearest_hospital' => 'Coron District Hospital',
                'website_url' => 'https://www.divingsquad.com/philippines-diving/palawan/coron/',
            ],
            [
                'name' => 'Nosy Be',
                'country' => 'Madagascar',
                'region' => 'Diana Region',
                'latitude' => -13.4012,
                'longitude' => 48.2718,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Indian Ocean / Mozambique Channel. Visibility 15-30m. Water temp 24-30°C. Best diving May-November (dry season). Strong currents possible.',
                'marine_life' => 'Whale sharks (Oct-Dec), manta rays, turtles, reef sharks, humpback whales (Jul-Sep). Pristine coral reefs around Nosy Tanikely marine reserve.',
                'access_notes' => 'Fly to Fascene Airport (NOS) via Antananarivo. Dive centers at Ambatoloaka and Hell-Ville. Nearby islands: Nosy Komba, Nosy Mitsio, Nosy Sakatia, Nosy Tanikely.',
                'facilities' => 'Several dive centers, equipment rental, Nitrox. Liveaboard options to Mitsio archipelago.',
                'website_url' => 'https://nosybe.dune-world.com',
            ],
            [
                'name' => 'L\'Estartit — Illes Medes',
                'country' => 'Spain',
                'region' => 'Costa Brava, Catalonia',
                'latitude' => 42.0501,
                'longitude' => 3.1962,
                'max_depth' => 50,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean marine reserve. Visibility 10-25m. Water temp 13-24°C. 10 buoyed dive sites around the 7 Medes Islands. Protected since 1983 — exceptional marine life density.',
                'marine_life' => 'Huge groupers (unafraid of divers), moray eels, eagle rays, barracuda, octopus, red coral, gorgonians. Dolphin Cave — cathedral-like chamber with light beams.',
                'access_notes' => 'L\'Estartit, Girona. AP-7 exit 6 (from Barcelona) or exit 3 (from France). Islands 1km offshore, 10min by boat.',
                'facilities' => 'Multiple dive centers in town. Marine park entry fee required.',
                'website_url' => 'https://www.padi.com/diving-in/spain/l-estartit/',
            ],
            [
                'name' => 'El Rey del Mar — L\'Estartit',
                'country' => 'Spain',
                'region' => 'Costa Brava, Catalonia',
                'latitude' => 42.0501,
                'longitude' => 3.1962,
                'max_depth' => 50,
                'water_type' => 'sea',
                'conditions' => 'Dive center inside Hotel Panorama, 50m from the beach. Boat dives to Medes Islands and Montgrí coast within the Natural Park.',
                'marine_life' => 'Groupers, moray eels, octopus, red coral, gorgonians, nudibranchs. Posidonia meadows on the coast.',
                'access_notes' => 'Hotel Panorama, Av. Grècia 5, 17258 L\'Estartit. GPS: 42.05012, 3.19622.',
                'facilities' => 'SSI & PADI courses, full rental, readaptation dives on Montgrí coast before reserve dives.',
                'website_url' => 'https://www.elreidelmar.com',
            ],
            [
                'name' => 'La Sirena Diving Center — L\'Estartit',
                'country' => 'Spain',
                'region' => 'Costa Brava, Catalonia',
                'latitude' => 42.0490,
                'longitude' => 3.1950,
                'max_depth' => 50,
                'water_type' => 'sea',
                'conditions' => 'Dive center in L\'Estartit. Boat dives to Medes Islands marine reserve — 7 islands including Meda Gran, Meda Petita, Carall Bernat.',
                'marine_life' => 'Groupers, moray eels, eagle rays, barracuda, octopus, red coral, gorgonians. Dolphin Cave on Meda Petita.',
                'access_notes' => 'L\'Estartit, Costa Brava. Approximately 1 mile from town to the islands.',
                'facilities' => 'Courses from beginner to professional, snorkeling trips, full rental.',
                'website_url' => 'https://divingcenterlasirena.com',
            ],
            [
                'name' => 'Safaga',
                'country' => 'Egypt',
                'region' => 'Red Sea',
                'latitude' => 26.7654,
                'longitude' => 33.9448,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Red Sea. Visibility 20-40m. Water temp 22-30°C. Less crowded than Hurghada. Famous for Salem Express wreck (30m), Panorama Reef, Tobia Arbaa. Strong currents on some sites.',
                'marine_life' => 'Dolphins, turtles, reef sharks, manta rays, huge gorgonian fans, soft corals. Salem Express wreck teeming with life.',
                'access_notes' => '60km south of Hurghada airport. Multiple dive centers and resorts along the coast.',
                'facilities' => 'Dive centers, Nitrox, liveaboard departures. Day trips to offshore reefs.',
                'nearest_hospital' => 'Safaga General Hospital',
                'website_url' => 'https://redsea.dune-world.com',
            ],
            [
                'name' => 'Sesimbra',
                'country' => 'Portugal',
                'region' => 'Setúbal, Lisbon Region',
                'latitude' => 38.4445,
                'longitude' => -9.1015,
                'max_depth' => 35,
                'water_type' => 'sea',
                'conditions' => 'Atlantic. Visibility 5-15m. Water temp 14-20°C. Wrecks and reefs off Arrábida Natural Park. Famous River Gurara wreck (Nigerian cargo ship, sunk 1989). Cold water — thick wetsuit or drysuit recommended.',
                'marine_life' => 'Octopus, conger eels, nudibranchs, seahorses, sunfish (Mola mola in season), schools of bream and bass.',
                'access_notes' => '40km south of Lisbon. Dive centers at Porto de Abrigo de Sesimbra. Boat dives.',
                'facilities' => 'Several dive centers, equipment rental, courses. Arrábida marine park.',
                'website_url' => 'https://scubago.com/europe/portugal/lisbon-region/setubal/sesimbra',
            ],
            [
                'name' => 'Peniche — Berlengas',
                'country' => 'Portugal',
                'region' => 'Leiria, Centro',
                'latitude' => 39.3558,
                'longitude' => -9.3811,
                'max_depth' => 30,
                'water_type' => 'sea',
                'conditions' => 'Atlantic. Visibility 5-20m. Water temp 14-19°C. Berlenga Grande island 30min by boat — marine reserve with caves, tunnels, arches. Exposed to Atlantic swell — weather dependent.',
                'marine_life' => 'Lobsters, octopus, conger eels, nudibranchs, wrasse, bream. Kelp forests. Occasional sunfish and dolphins.',
                'access_notes' => 'Peniche, 90km north of Lisbon. Dive centers at the fishing port. Boat to Berlengas. Camping and restaurant on the island.',
                'facilities' => 'Dive centers with boat access, equipment rental, courses.',
                'website_url' => 'https://www.padi.com/diving-in/portugal/peniche/',
            ],
            // ── Batch 2 ──────────────────────────────────────────
            [
                'name' => 'Brother Islands',
                'country' => 'Egypt',
                'region' => 'Red Sea',
                'latitude' => 26.3200,
                'longitude' => 34.8500,
                'max_depth' => 80,
                'water_type' => 'sea',
                'conditions' => 'Red Sea offshore. Visibility 20-40m. Water temp 22-28°C. Two tiny islands (Big & Little Brother) — exposed tips of massive reef pillars from abyssal depths. Liveaboard only, 200km south of Ras Mohammed. Strong currents, advanced divers.',
                'marine_life' => 'Oceanic whitetip sharks, hammerheads, thresher sharks, grey reef sharks, manta rays. Aida wreck on Big Brother (30-80m). Pristine soft coral walls.',
                'access_notes' => 'Liveaboard from Hurghada or Marsa Alam. No shore access. Weather dependent.',
                'facilities' => 'Liveaboard only. Mooring buoys.',
            ],
            [
                'name' => 'Curaçao',
                'country' => 'Curaçao',
                'region' => 'Caribbean, ABC Islands',
                'latitude' => 12.1696,
                'longitude' => -68.9900,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Caribbean. Visibility 20-40m. Water temp 26-29°C year-round. Shore diving paradise — 65+ dive sites accessible from shore. Gentle currents, calm conditions. Reef drops off steeply from shore.',
                'marine_life' => 'Turtles, seahorses, frogfish, octopus, moray eels, tarpon, barracuda. Pristine coral reefs, sponge gardens. Mushroom Forest famous site.',
                'access_notes' => 'Fly to Hato Airport (CUR). Dive sites all along the leeward coast. Easy shore entry at most sites.',
                'facilities' => 'Many dive centers, shore diving with truck/tank service, Nitrox widely available.',
            ],
            [
                'name' => 'Cocos Island (Isla del Coco)',
                'country' => 'Costa Rica',
                'region' => 'Pacific Ocean',
                'latitude' => 5.5168,
                'longitude' => -87.0697,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Open Pacific. Visibility 10-30m. Water temp 24-30°C. UNESCO World Heritage. 550km offshore — liveaboard only (36h crossing). ~20 dive sites around the island. Strong currents, advanced divers. Thermoclines.',
                'marine_life' => 'Schooling scalloped hammerheads (hundreds), whale sharks, manta rays, dolphins, Galápagos sharks, marble rays, whitetip reef sharks. Bajo Alcyone seamount at 27m.',
                'access_notes' => 'Liveaboard from Puntarenas, Costa Rica. 36-hour crossing each way. Trips typically 10 days.',
                'facilities' => 'Liveaboard only. National park — no facilities on island.',
            ],
            [
                'name' => 'Mega Dive — Sesimbra',
                'country' => 'Portugal',
                'region' => 'Setúbal, Lisbon Region',
                'latitude' => 38.4440,
                'longitude' => -9.1020,
                'max_depth' => 35,
                'water_type' => 'sea',
                'conditions' => 'Atlantic. Dive center at Porto de Abrigo de Sesimbra, integrated in Parque Marinho Prof. Luiz Saldanha. Boat dives to Arrábida marine reserve.',
                'marine_life' => 'Octopus, conger eels, nudibranchs, seahorses, sunfish (Mola mola). Wreck of River Gurara.',
                'access_notes' => 'Av. dos Náufragos, Armazém 2 e 3, Bloco D, 2970-152 Sesimbra.',
                'facilities' => 'Dive school, nautical events, equipment rental, courses. Kayaking and dolphin watching also available.',
                'website_url' => 'https://www.megadive.pt',
            ],
            [
                'name' => 'Port-Cros',
                'country' => 'France',
                'region' => 'Var, Côte d\'Azur',
                'latitude' => 43.0044,
                'longitude' => 6.3936,
                'max_depth' => 45,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 15-30m. Water temp 14-25°C. National marine park since 1963 — oldest in Europe. Protected waters with exceptional biodiversity. Grouper reserve.',
                'marine_life' => 'Large groupers (protected, very approachable), barracuda, moray eels, eagle rays, dentex. Posidonia meadows, gorgonians, red coral. La Gabinière — world-class wall dive.',
                'access_notes' => 'Boat from Hyères, Le Lavandou, or Bormes-les-Mimosas. ~20min crossing. Dive permit required from park authority.',
                'facilities' => 'Dive centers on the mainland. Limited facilities on the island. Marine park regulations apply.',
            ],
            [
                'name' => 'Cape Verde (Sal)',
                'country' => 'Cape Verde',
                'region' => 'Sal Island, Atlantic',
                'latitude' => 16.7260,
                'longitude' => -22.9340,
                'max_depth' => 35,
                'water_type' => 'sea',
                'conditions' => 'Atlantic/tropical. Visibility 15-30m. Water temp 22-27°C. Volcanic underwater landscapes, caves, arches, tunnels. Mild currents on most sites.',
                'marine_life' => 'Nurse sharks, lemon sharks, manta rays, turtles, moray eels, whale sharks (seasonal). Volcanic rock formations with rich marine life.',
                'access_notes' => 'Fly to Sal (SID) or Boa Vista. Dive centers in Santa Maria (Sal).',
                'facilities' => 'Several dive centers, equipment rental, courses. Nitrox available.',
            ],
            [
                'name' => 'Silfra Fissure',
                'country' => 'Iceland',
                'region' => 'Þingvellir National Park',
                'latitude' => 64.2558,
                'longitude' => -21.1164,
                'max_depth' => 18,
                'water_type' => 'freshwater',
                'conditions' => 'Glacial spring water. Visibility 80-100m+ (clearest water on Earth). Water temp 2-4°C year-round. Drysuit mandatory. Dive between the North American and Eurasian tectonic plates — only place in the world.',
                'marine_life' => 'Minimal — bright green algae (troll hair), some Arctic char. The attraction is the geology and visibility, not marine life.',
                'access_notes' => 'Þingvellir National Park, 60km from Reykjavik. Silfra car park. Drysuit certification required.',
                'facilities' => 'Dive operators provide all equipment. Changing facilities at car park. No fills on site.',
            ],
            [
                'name' => 'Guadeloupe — Réserve Cousteau',
                'country' => 'France',
                'region' => 'Guadeloupe, Caribbean',
                'latitude' => 16.1670,
                'longitude' => -61.7890,
                'max_depth' => 30,
                'water_type' => 'sea',
                'conditions' => 'Caribbean. Visibility 15-30m. Water temp 26-29°C. Réserve Cousteau off Pigeon Island (Bouillante) — named after Jacques Cousteau who filmed here. Protected marine area.',
                'marine_life' => 'Turtles, seahorses, barracuda, parrotfish, angelfish, lobsters. Coral gardens, sponges. Occasional dolphins and rays.',
                'access_notes' => 'Fly to Pointe-à-Pitre (PTP). Dive centers in Bouillante and Malendure beach. Boat to Pigeon Island in 5min.',
                'facilities' => 'Multiple dive centers, equipment rental, courses. Glass-bottom boats for non-divers.',
            ],
            [
                'name' => 'Martinique',
                'country' => 'France',
                'region' => 'Martinique, Caribbean',
                'latitude' => 14.6415,
                'longitude' => -61.0242,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Caribbean. Visibility 15-30m. Water temp 26-29°C. Volcanic underwater landscapes. Famous for the 1902 eruption wrecks in Saint-Pierre bay — 14 ships sunk by pyroclastic flow from Mont Pelée.',
                'marine_life' => 'Turtles, seahorses, frogfish, barracuda, nurse sharks. Coral-encrusted wrecks. Diamond Rock — dramatic volcanic pinnacle.',
                'access_notes' => 'Fly to Fort-de-France (FDF). Dive centers in Saint-Pierre, Les Anses-d\'Arlet, Le Diamant.',
                'facilities' => 'Multiple dive centers, equipment rental, courses. Wreck diving specialty.',
            ],
            [
                'name' => 'Extra Divers — Jebel Sifah, Oman',
                'country' => 'Oman',
                'region' => 'Muscat Governorate',
                'latitude' => 23.4800,
                'longitude' => 58.7300,
                'max_depth' => 30,
                'water_type' => 'sea',
                'conditions' => 'Gulf of Oman. Visibility 5-20m (variable). Water temp 22-32°C. Whale sharks Jul-Nov. Munassir wreck, Fahal Islands, Ras Abu Daoud reefs. German-managed center.',
                'marine_life' => 'Whale sharks (seasonal), turtles, cuttlefish, nudibranchs, schools of jacks and barracuda. Reef sharks, eagle rays.',
                'access_notes' => 'Sifawy Boutique Resort, Jebel Sifah, <1h from Muscat. 2-tank boat dives departing 9am.',
                'facilities' => 'Full dive center by Extra Divers Worldwide. Equipment rental, Nitrox, courses.',
                'website_url' => 'https://sifawyhotel.com/extra-divers-dive-centre-at-jebel-sifah/',
            ],
            [
                'name' => 'OK Maldives (Liveaboard)',
                'country' => 'Maldives',
                'region' => 'Indian Ocean',
                'latitude' => 4.1755,
                'longitude' => 73.5093,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Indian Ocean. Visibility 15-40m. Water temp 27-30°C year-round. 26 atolls, channel dives with current. Best Jan-Apr (NE monsoon, mantas) and Aug-Nov (SW monsoon, whale sharks).',
                'marine_life' => 'Manta rays, whale sharks, hammerheads, grey reef sharks, eagle rays, turtles, dolphins. Pristine coral reefs in channels (kandus).',
                'access_notes' => 'Fly to Malé (MLE). Liveaboard departures from Malé harbor. Typical 7-10 day itineraries.',
                'facilities' => 'Liveaboard with full dive deck, Nitrox, equipment rental.',
            ],
            [
                'name' => 'Les Amis des Maldives (Liveaboard)',
                'country' => 'Maldives',
                'region' => 'Indian Ocean',
                'latitude' => 4.1755,
                'longitude' => 73.5093,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Diving cruise operator. Ocean One vessel (37m × 12m, 3 decks). Up to 3 dives/day on the best spots of each atoll. PADI & CMAS training available on board.',
                'marine_life' => 'Grey & whitetip sharks, eagle rays, mantas, whale sharks, dolphins, turtles, napoleons. Ocean passes and drop-offs.',
                'access_notes' => 'Depart from Malé. Cruises across multiple atolls (north and south itineraries).',
                'facilities' => 'Liveaboard with jacuzzi, spacious decks, en-suite cabins. PADI OW/AOW, CMAS PE40/N2, Nitrox training.',
                'website_url' => 'https://www.amisdesmaldives.com',
            ],
            [
                'name' => 'L\'Océanos (Liveaboard Égypte)',
                'country' => 'Egypt',
                'region' => 'Red Sea',
                'latitude' => 27.1780,
                'longitude' => 33.8414,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Red Sea liveaboard. M/Y Oceanos (39m), 13 cabins for 26 divers. Safari routes: Brothers, Daedalus, Elphinstone, Fury Shoals, St. John\'s.',
                'marine_life' => 'Sharks (oceanic whitetip, hammerhead, grey reef), dolphins, mantas, turtles. Pristine coral walls, wrecks.',
                'access_notes' => 'Departs from Hurghada. Typical 7-day safari routes.',
                'facilities' => 'Full dive deck, Nitrox, equipment rental, en-suite cabins with A/C.',
            ],
            [
                'name' => 'Carrière de Rochefontaine',
                'country' => 'Belgium',
                'region' => 'Namur, Wallonia',
                'latitude' => 50.2700,
                'longitude' => 4.6200,
                'max_depth' => 35,
                'water_type' => 'quarry',
                'conditions' => 'Flooded quarry. Visibility 3-8m. Water temp 4-18°C. Platforms at various depths. Training site for Belgian clubs.',
                'marine_life' => 'Pike, perch, carp, trout. Crayfish.',
                'access_notes' => 'Rochefontaine, Namur province. Club access — check opening schedule.',
                'facilities' => 'Changing rooms, parking, fill station nearby.',
            ],
            [
                'name' => 'Carrière de Villers-deux-Églises',
                'country' => 'Belgium',
                'region' => 'Namur, Wallonia',
                'latitude' => 50.2100,
                'longitude' => 4.5600,
                'max_depth' => 20,
                'water_type' => 'quarry',
                'conditions' => 'Flooded quarry. Visibility 3-6m. Water temp 4-18°C. Popular training site for Belgian and Luxembourg clubs.',
                'marine_life' => 'Pike, perch, carp.',
                'access_notes' => 'Villers-deux-Églises, Namur province. Club access.',
                'facilities' => 'Basic facilities, parking.',
            ],
            [
                'name' => 'Remerschen — Baggerweieren',
                'country' => 'Luxembourg',
                'region' => 'Moselle, Schengen',
                'latitude' => 49.4950,
                'longitude' => 6.3580,
                'max_depth' => 8,
                'water_type' => 'lake',
                'conditions' => 'Former gravel pit lakes. Visibility 2-5m. Water temp 10-24°C. Shallow — good for training and try-dives. Swimming area with entry fee (€6 adults). Algae blooms possible in summer.',
                'marine_life' => 'Carp, pike, perch. Freshwater mussels.',
                'access_notes' => 'Remerschen, near Schengen. 25ha site with beaches, parking. Entry fee applies.',
                'facilities' => 'Toilets, changing areas, beach volleyball, playground. Restaurant nearby.',
                'website_url' => 'https://www.visitluxembourg.com/place/remerschen-lakes',
            ],
            // ── Batch 3 ──────────────────────────────────────────
            [
                'name' => 'Orca Diving — Ustica',
                'country' => 'Italy',
                'region' => 'Sicily, Tyrrhenian Sea',
                'latitude' => 38.7108,
                'longitude' => 13.1800,
                'max_depth' => 50,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 20-40m. Water temp 15-27°C. Marine Protected Area — Italy\'s first (1986). Volcanic island 67km NW of Palermo. Walls, caves, shoals. Colombara Shoal, Secca d\'Africa, Punta San Paolo.',
                'marine_life' => 'Groupers, barracuda, amberjack, moray eels, octopus. Orange Astroides coral, gorgonians. Occasional dolphins, tuna.',
                'access_notes' => 'Ferry/hydrofoil from Palermo (~1h30). Dive center at the harbour, walking distance from accommodation.',
                'facilities' => 'PADI dive center, equipment rental, boats to all sites in minutes. Courses from baptism to advanced.',
                'website_url' => 'https://www.orcadivingustica.com',
            ],
            [
                'name' => 'L\'Incantu — Galéria',
                'country' => 'France',
                'region' => 'Haute-Corse, Corsica',
                'latitude' => 42.4200,
                'longitude' => 8.6400,
                'max_depth' => 60,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 15-30m. Water temp 14-25°C. Gateway to Réserve Naturelle de Scandola (UNESCO). Largest dive center in Corsica — 6 boats, ~25,000 dives/year. FFESSM, PADI, CMAS approved.',
                'marine_life' => 'Groupers, dentex, barracuda, moray eels, lobsters. Red coral, gorgonians. Scandola\'s protected waters teem with life.',
                'access_notes' => 'Galéria, Haute-Corse. Residence with apartments, heated pool, restaurant. Meet at 8:30 and 14:30 for dive trips.',
                'facilities' => 'Full dive center, equipment rental, courses up to N4/Dive Guide. Accommodation + diving packages.',
                'website_url' => 'https://www.incantu.com',
            ],
            [
                'name' => 'Dive4Life — Siegburg',
                'country' => 'Germany',
                'region' => 'North Rhine-Westphalia',
                'latitude' => 50.7930,
                'longitude' => 7.2030,
                'max_depth' => 20,
                'water_type' => 'pool',
                'conditions' => 'Indoor diving tower. 3 million litres crystal-clear heated water at 26°C. 20m deep, 10m diameter. Maya-themed décor with caves, grottos, and a wreck. Year-round perfect conditions. Germany\'s largest heated indoor diving center.',
                'marine_life' => 'None — indoor facility.',
                'access_notes' => 'Siegburg, near Bonn. Easy access from A3/A560. Parking on site.',
                'facilities' => 'Full dive center, equipment rental, courses, restaurant, hotel partnership (Stay & Dive packages). Events and Nitrox.',
                'website_url' => 'https://www.dive4life.de',
            ],
            [
                'name' => 'Boschmolenplas — Heel',
                'country' => 'Netherlands',
                'region' => 'Limburg',
                'latitude' => 51.1800,
                'longitude' => 5.9000,
                'max_depth' => 28,
                'water_type' => 'lake',
                'conditions' => 'Freshwater lake. Visibility up to 12m (excellent for NL). Privately run dive site with submerged artificial objects and attractions. Rich underwater flora and fauna.',
                'marine_life' => 'Pike, perch, carp, crayfish. Abundant aquatic plants.',
                'access_notes' => 'Heel, Limburg province (south Netherlands). Private site — check opening hours and entry requirements.',
                'facilities' => 'Parking, entry facilities. Privately managed.',
            ],
            // ── Batch 4 — Luxembourg (5 new) ────────────────────
            [
                'name' => 'Lac de la Haute-Sûre — Liefrange',
                'country' => 'Luxembourg',
                'region' => 'Haute-Sûre',
                'latitude' => 49.9100,
                'longitude' => 5.8900,
                'max_depth' => 30,
                'water_type' => 'lake',
                'conditions' => 'Submerged village of Liefrange — houses, bridges, roads flooded when the dam was built. Visibility 3-8m. Water temp 5-20°C.',
                'marine_life' => 'Pike, perch, carp, trout.',
                'access_notes' => 'Lac de la Haute-Sûre, near Liefrange. Accessible from Lultzhausen entry.',
            ],
            [
                'name' => 'Lac de Weiswampach',
                'country' => 'Luxembourg',
                'region' => 'Clervaux, Éislek',
                'latitude' => 50.1350,
                'longitude' => 6.0750,
                'max_depth' => 6,
                'water_type' => 'lake',
                'conditions' => 'Two recreational lakes in northern Luxembourg. Shallow, good for training and try-dives. Visibility 2-5m. Water temp 10-22°C.',
                'marine_life' => 'Carp, perch, pike. Freshwater mussels.',
                'access_notes' => 'Weiswampach, near Belgian border. Leisure center with beach access.',
                'facilities' => 'Beach, camping, restaurant, parking. Entry fee applies.',
            ],
            [
                'name' => 'Lac d\'Echternach',
                'country' => 'Luxembourg',
                'region' => 'Mullerthal',
                'latitude' => 49.8120,
                'longitude' => 6.4230,
                'max_depth' => 5,
                'water_type' => 'lake',
                'conditions' => 'Artificial lake in Echternach. Very shallow — training and try-dives only. Visibility 2-4m.',
                'marine_life' => 'Carp, roach, perch.',
                'access_notes' => 'Echternach lake, next to the town center. Leisure area.',
                'facilities' => 'Beach, pedal boats, playground, restaurants nearby.',
            ],
            [
                'name' => 'Moselle — Remich',
                'country' => 'Luxembourg',
                'region' => 'Moselle',
                'latitude' => 49.5450,
                'longitude' => 6.3670,
                'max_depth' => 8,
                'water_type' => 'river',
                'conditions' => 'Moselle river. Visibility 1-3m (poor). Current variable. Training dives only. Water temp 8-22°C.',
                'marine_life' => 'Carp, pike, zander, catfish.',
                'access_notes' => 'Remich, along the Moselle promenade. Check river conditions before diving.',
            ],
            [
                'name' => 'Lac de la Haute-Sûre — Pont Misère',
                'country' => 'Luxembourg',
                'region' => 'Haute-Sûre',
                'latitude' => 49.9050,
                'longitude' => 5.8600,
                'max_depth' => 25,
                'water_type' => 'lake',
                'conditions' => 'Entry point on the Haute-Sûre reservoir. Submerged bridge remains. Visibility 3-8m. Steep drop-off.',
                'marine_life' => 'Pike, perch, carp, trout.',
                'access_notes' => 'Pont Misère area, Lac de la Haute-Sûre. Parking nearby.',
            ],
            // ── Batch 4 — Belgium (15 new) ───────────────────────
            [
                'name' => 'Carrière de La Gombe',
                'country' => 'Belgium',
                'region' => 'Liège, Wallonia',
                'latitude' => 50.5500,
                'longitude' => 5.5200,
                'max_depth' => 30,
                'water_type' => 'quarry',
                'conditions' => 'Limestone quarry near Esneux. Visibility 10-12m (excellent for Belgium). Water temp 4-18°C. Stunning rock formations.',
                'marine_life' => 'Pike, perch, carp, trout, crayfish.',
                'access_notes' => 'Near Esneux, close to Liège. Club access.',
                'facilities' => 'Changing rooms, parking, fill station.',
            ],
            [
                'name' => 'Carrière de Barvaux',
                'country' => 'Belgium',
                'region' => 'Luxembourg, Wallonia',
                'latitude' => 50.3500,
                'longitude' => 5.5000,
                'max_depth' => 20,
                'water_type' => 'quarry',
                'conditions' => 'Flooded quarry in the Ardennes. Visibility 3-8m. Water temp 4-18°C. Platforms at various depths.',
                'marine_life' => 'Pike, perch, carp.',
                'access_notes' => 'Barvaux-sur-Ourthe, Luxembourg province.',
                'facilities' => 'Basic facilities, parking.',
            ],
            [
                'name' => 'Carrière de Halanzy',
                'country' => 'Belgium',
                'region' => 'Luxembourg, Wallonia',
                'latitude' => 49.5700,
                'longitude' => 5.7400,
                'max_depth' => 15,
                'water_type' => 'quarry',
                'conditions' => 'Small flooded quarry near Luxembourg border. Visibility 3-6m. Good training site.',
                'marine_life' => 'Pike, perch, carp.',
                'access_notes' => 'Halanzy, near Aubange. Close to Luxembourg border.',
                'facilities' => 'Basic facilities.',
            ],
            [
                'name' => 'Lac de Bütgenbach',
                'country' => 'Belgium',
                'region' => 'Liège, East Belgium',
                'latitude' => 50.4250,
                'longitude' => 6.2850,
                'max_depth' => 20,
                'water_type' => 'lake',
                'conditions' => 'Reservoir lake in East Belgium. Visibility 3-6m. Water temp 5-18°C. Scenic Ardennes setting.',
                'marine_life' => 'Pike, perch, trout, carp.',
                'access_notes' => 'Bütgenbach, German-speaking community. Leisure area.',
                'facilities' => 'Beach, camping, restaurants nearby.',
            ],
            [
                'name' => 'Lac de Robertville',
                'country' => 'Belgium',
                'region' => 'Liège, East Belgium',
                'latitude' => 50.4500,
                'longitude' => 6.1300,
                'max_depth' => 25,
                'water_type' => 'lake',
                'conditions' => 'Reservoir lake near Malmedy. Visibility 3-6m. Water temp 5-18°C. Deeper than Bütgenbach.',
                'marine_life' => 'Pike, perch, trout.',
                'access_notes' => 'Robertville, near Malmedy. Parking at the dam.',
            ],
            [
                'name' => 'Carrière de Ekeren',
                'country' => 'Belgium',
                'region' => 'Antwerp, Flanders',
                'latitude' => 51.2800,
                'longitude' => 4.4200,
                'max_depth' => 12,
                'water_type' => 'quarry',
                'conditions' => 'Flooded clay pit near Antwerp. Visibility 2-5m. Shallow — good for training. Submerged objects.',
                'marine_life' => 'Perch, carp, eel.',
                'access_notes' => 'Ekeren, north of Antwerp. Club access.',
                'facilities' => 'Changing rooms, parking.',
            ],
            [
                'name' => 'Lac de Falemprise',
                'country' => 'Belgium',
                'region' => 'Hainaut, Wallonia',
                'latitude' => 50.3200,
                'longitude' => 4.3800,
                'max_depth' => 20,
                'water_type' => 'lake',
                'conditions' => 'Artificial lake near Cerfontaine. Visibility 3-6m. Water temp 5-18°C. Popular with Belgian clubs.',
                'marine_life' => 'Pike, perch, carp, trout.',
                'access_notes' => 'Cerfontaine, Hainaut province. Leisure area.',
                'facilities' => 'Beach, camping, parking.',
            ],
            [
                'name' => 'Carrière de Denée (Mine)',
                'country' => 'Belgium',
                'region' => 'Namur, Wallonia',
                'latitude' => 50.3000,
                'longitude' => 4.6700,
                'max_depth' => 40,
                'water_type' => 'quarry',
                'conditions' => 'Flooded black marble mine. Cave diving — advanced/tech only. Huge underground halls and corridors. Visibility 5-10m in clear water.',
                'marine_life' => 'None — underground mine.',
                'access_notes' => 'Denée, near Anhée. Restricted access — cave diving certification required.',
                'facilities' => 'Minimal. Experienced cave divers only.',
            ],
            [
                'name' => 'Zilvermeer — Mol',
                'country' => 'Belgium',
                'region' => 'Antwerp, Flanders',
                'latitude' => 51.2000,
                'longitude' => 5.1000,
                'max_depth' => 15,
                'water_type' => 'lake',
                'conditions' => 'Provincial recreation domain. Visibility 3-6m. Shallow lake with sandy bottom. Good for training.',
                'marine_life' => 'Perch, carp, pike.',
                'access_notes' => 'Mol, Antwerp province. Provincial domain — entry fee.',
                'facilities' => 'Beach, camping, restaurant, parking.',
            ],
            [
                'name' => 'Blaarmeersen — Gent',
                'country' => 'Belgium',
                'region' => 'East Flanders',
                'latitude' => 51.0400,
                'longitude' => 3.6800,
                'max_depth' => 10,
                'water_type' => 'lake',
                'conditions' => 'Urban recreation lake in Ghent. Visibility 2-5m. Shallow — training and try-dives.',
                'marine_life' => 'Perch, carp, eel.',
                'access_notes' => 'Blaarmeersen sport park, Ghent. Entry fee.',
                'facilities' => 'Beach, sports facilities, restaurant, parking.',
            ],
            [
                'name' => 'Lac de l\'Eau d\'Heure',
                'country' => 'Belgium',
                'region' => 'Hainaut/Namur, Wallonia',
                'latitude' => 50.1800,
                'longitude' => 4.3700,
                'max_depth' => 30,
                'water_type' => 'lake',
                'conditions' => 'Largest lake complex in Belgium. 5 interconnected lakes. Visibility 3-6m. Water temp 5-18°C.',
                'marine_life' => 'Pike, perch, carp, trout, zander.',
                'access_notes' => 'Eau d\'Heure lakes, between Hainaut and Namur. Multiple access points.',
                'facilities' => 'Marina, beach, camping, restaurants, water sports center.',
            ],
            [
                'name' => 'Carrière de Spontin',
                'country' => 'Belgium',
                'region' => 'Namur, Wallonia',
                'latitude' => 50.3300,
                'longitude' => 5.0000,
                'max_depth' => 18,
                'water_type' => 'quarry',
                'conditions' => 'Flooded quarry near Spontin. Visibility 3-8m. Platforms and submerged objects.',
                'marine_life' => 'Pike, perch, carp.',
                'access_notes' => 'Spontin, Namur province. Club access.',
                'facilities' => 'Basic facilities, parking.',
            ],
            [
                'name' => 'Carrière de Amblève',
                'country' => 'Belgium',
                'region' => 'Liège, Wallonia',
                'latitude' => 50.4000,
                'longitude' => 5.8500,
                'max_depth' => 25,
                'water_type' => 'quarry',
                'conditions' => 'Flooded quarry in the Amblève valley. Visibility 3-8m. Popular training site.',
                'marine_life' => 'Pike, perch, carp, trout.',
                'access_notes' => 'Amblève valley, Liège province.',
                'facilities' => 'Basic facilities, parking.',
            ],
            [
                'name' => 'Zeelandbrug — Zierikzee',
                'country' => 'Belgium',
                'region' => 'Zeeland (cross-border)',
                'latitude' => 51.6300,
                'longitude' => 3.9100,
                'max_depth' => 25,
                'water_type' => 'sea',
                'conditions' => 'Oosterschelde near the Zeeland Bridge. Strong tidal currents — plan around slack water. Visibility 3-10m. Famous for cuttlefish mating (May-Jun).',
                'marine_life' => 'Cuttlefish, lobsters, seahorses, anemones, nudibranchs, crabs.',
                'access_notes' => 'Near Zierikzee. Popular with Belgian and Dutch clubs. Tide tables essential.',
                'facilities' => 'Parking, easy shore entry from bridge pillars.',
            ],
            [
                'name' => 'Strépy-Bracquegnies (Canal du Centre)',
                'country' => 'Belgium',
                'region' => 'Hainaut, Wallonia',
                'latitude' => 50.4800,
                'longitude' => 4.0900,
                'max_depth' => 10,
                'water_type' => 'canal',
                'conditions' => 'Canal near the famous boat lifts. Visibility 1-3m. Shallow — training dives. UNESCO World Heritage area.',
                'marine_life' => 'Carp, perch, eel.',
                'access_notes' => 'Strépy-Bracquegnies, near La Louvière.',
                'facilities' => 'Parking. Near boat lift visitor center.',
            ],
            // ── Batch 4 — France (10 new) ────────────────────────
            [
                'name' => 'Marseille — Calanques (Riou)',
                'country' => 'France',
                'region' => 'Bouches-du-Rhône, Provence',
                'latitude' => 43.1740,
                'longitude' => 5.3930,
                'max_depth' => 45,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Calanques National Park. Visibility 15-30m. Water temp 13-25°C. Riou & Planier archipelagos — 50+ dive sites. Gorgonian walls, caves, wrecks.',
                'marine_life' => 'Groupers, barracuda, moray eels, octopus, scorpionfish. Red coral, gorgonians. Mérou de Riou famous.',
                'access_notes' => 'Boat from Marseille Vieux-Port or Pointe-Rouge. Multiple dive centers.',
                'facilities' => 'Many dive centers, equipment rental, Nitrox. Courses all levels.',
            ],
            [
                'name' => 'Île du Levant — Hyères',
                'country' => 'France',
                'region' => 'Var, Côte d\'Azur',
                'latitude' => 43.0280,
                'longitude' => 6.4650,
                'max_depth' => 45,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Part of Îles d\'Hyères (Îles d\'Or). Visibility 15-30m. Water temp 14-25°C. Walls, caves, wrecks. Le Donator wreck (47m) — iconic French dive.',
                'marine_life' => 'Groupers, barracuda, dentex, eagle rays, moray eels. Gorgonians, red coral.',
                'access_notes' => 'Boat from Hyères, Le Lavandou, or Port-Cros. Dive centers on the mainland.',
            ],
            [
                'name' => 'Le Lavandou',
                'country' => 'France',
                'region' => 'Var, Côte d\'Azur',
                'latitude' => 43.1370,
                'longitude' => 6.3700,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 15-25m. Water temp 14-25°C. Gateway to Îles d\'Hyères. Many wrecks: Donator, Togo, Grec, Michel C.',
                'marine_life' => 'Groupers, barracuda, moray eels, octopus. Gorgonians, posidonia meadows.',
                'access_notes' => 'Le Lavandou harbour. Multiple dive centers.',
                'facilities' => 'Dive centers, equipment rental, courses. Nitrox available.',
            ],
            [
                'name' => 'Cerbère-Banyuls Marine Reserve',
                'country' => 'France',
                'region' => 'Pyrénées-Orientales, Occitanie',
                'latitude' => 42.4700,
                'longitude' => 3.1600,
                'max_depth' => 30,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. France\'s first marine reserve (1974). Visibility 10-25m. Water temp 13-24°C. Côte Vermeille — rocky coast near Spanish border.',
                'marine_life' => 'Groupers, barracuda, moray eels, octopus, nudibranchs. Posidonia meadows, gorgonians.',
                'access_notes' => 'Cerbère or Banyuls-sur-Mer. Snorkeling trail at Peyrefite beach.',
                'facilities' => 'Dive centers, equipment rental, courses.',
            ],
            [
                'name' => 'Nice — Tombant des Américains',
                'country' => 'France',
                'region' => 'Alpes-Maritimes, Côte d\'Azur',
                'latitude' => 43.6800,
                'longitude' => 7.2900,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 15-30m. Water temp 14-25°C. Dramatic wall dive dropping from 6m to 40m+. Named after WWII American troops.',
                'marine_life' => 'Moray eels, crayfish, groupers, barracuda, nudibranchs. Gorgonians, sponges.',
                'access_notes' => 'Boat from Nice harbour. Multiple dive centers.',
                'facilities' => 'Many dive centers, equipment rental, courses.',
            ],
            [
                'name' => 'Arromanches — Épaves du D-Day',
                'country' => 'France',
                'region' => 'Calvados, Normandie',
                'latitude' => 49.3400,
                'longitude' => -0.6200,
                'max_depth' => 25,
                'water_type' => 'sea',
                'conditions' => 'English Channel. Visibility 3-10m. Water temp 10-18°C. 4500+ wrecks along Normandy coast. Mulberry harbour remains, USS Susan B. Anthony. Strong tidal currents.',
                'marine_life' => 'Lobsters, crabs, conger eels, wrasse, pollack. Wreck-encrusted marine life.',
                'access_notes' => 'Arromanches-les-Bains. Dive with local operators — tides critical.',
                'facilities' => 'Dive centers, equipment rental. D-Day museum nearby.',
            ],
            [
                'name' => 'Golfe de Porto — Scandola',
                'country' => 'France',
                'region' => 'Corse-du-Sud, Corsica',
                'latitude' => 42.3700,
                'longitude' => 8.5500,
                'max_depth' => 50,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. UNESCO World Heritage. Visibility 20-40m. Water temp 14-25°C. Volcanic red rock formations, caves, arches. Scandola reserve — restricted access.',
                'marine_life' => 'Groupers, dentex, barracuda, eagle rays, lobsters. Red coral, gorgonians.',
                'access_notes' => 'Boat from Porto, Galéria, or Cargèse. Dive permit required in reserve.',
            ],
            [
                'name' => 'Lac du Bourget',
                'country' => 'France',
                'region' => 'Savoie, Auvergne-Rhône-Alpes',
                'latitude' => 45.7450,
                'longitude' => 5.8600,
                'max_depth' => 145,
                'water_type' => 'lake',
                'conditions' => 'France\'s largest natural lake. Visibility 5-15m. Water temp 6-22°C. Steep drop-offs, submerged cliffs. Altitude diving.',
                'marine_life' => 'Pike, perch, char, lavaret, crayfish.',
                'access_notes' => 'Multiple entry points around the lake. Aix-les-Bains, Le Bourget-du-Lac.',
                'facilities' => 'Dive centers, equipment rental. Lakeside restaurants.',
            ],
            [
                'name' => 'Lac d\'Annecy',
                'country' => 'France',
                'region' => 'Haute-Savoie, Auvergne-Rhône-Alpes',
                'latitude' => 45.8610,
                'longitude' => 6.1690,
                'max_depth' => 82,
                'water_type' => 'lake',
                'conditions' => 'One of Europe\'s purest lakes. Visibility 10-20m (exceptional). Water temp 6-22°C. Steep walls, submerged trees.',
                'marine_life' => 'Pike, perch, char, trout, crayfish.',
                'access_notes' => 'Multiple entry points. Annecy, Talloires, Menthon-Saint-Bernard.',
                'facilities' => 'Dive centers, equipment rental.',
            ],
            [
                'name' => 'Étretat — Falaises',
                'country' => 'France',
                'region' => 'Seine-Maritime, Normandie',
                'latitude' => 49.7070,
                'longitude' => 0.2050,
                'max_depth' => 25,
                'water_type' => 'sea',
                'conditions' => 'English Channel. Visibility 3-10m. Water temp 10-18°C. Dive beneath the famous chalk cliffs and arches. Tidal currents.',
                'marine_life' => 'Lobsters, crabs, conger eels, wrasse, cuttlefish, pollack.',
                'access_notes' => 'Étretat beach. Shore entry possible at low tide. Check conditions.',
            ],
            // ── Batch 4 — Germany (10 new) ───────────────────────
            [
                'name' => 'Kreidesee Hemmoor',
                'country' => 'Germany',
                'region' => 'Lower Saxony',
                'latitude' => 53.6900,
                'longitude' => 9.1400,
                'max_depth' => 60,
                'water_type' => 'quarry',
                'conditions' => 'Flooded chalk quarry. Visibility up to 25m (Germany\'s best). Water temp 4-18°C. Platforms, submerged forest, vehicles. Germany\'s most popular freshwater dive site.',
                'marine_life' => 'Pike, perch, eel, crayfish. Abundant aquatic plants.',
                'access_notes' => 'Hemmoor, ~55km west of Hamburg. Well-organized dive site with entry fee.',
                'facilities' => 'Full dive center, fill station, equipment rental, changing rooms, restaurant, camping.',
                'website_url' => 'https://www.kreideseetaucher.de',
            ],
            [
                'name' => 'Bodensee (Lake Constance)',
                'country' => 'Germany',
                'region' => 'Baden-Württemberg',
                'latitude' => 47.6300,
                'longitude' => 9.3700,
                'max_depth' => 254,
                'water_type' => 'lake',
                'conditions' => 'Central Europe\'s third-largest lake. Visibility 5-15m. Water temp 5-22°C. Steep walls, wrecks (Jura, Helvetia). Shared with Switzerland and Austria.',
                'marine_life' => 'Pike, perch, char, whitefish, crayfish.',
                'access_notes' => 'Multiple entry points: Überlingen, Meersburg, Konstanz, Friedrichshafen.',
                'facilities' => 'Dive centers, fill stations, equipment rental.',
            ],
            [
                'name' => 'Stechlin See',
                'country' => 'Germany',
                'region' => 'Brandenburg',
                'latitude' => 53.1500,
                'longitude' => 13.0300,
                'max_depth' => 69,
                'water_type' => 'lake',
                'conditions' => 'Brandenburg\'s deepest lake. Visibility up to 10m. Water temp 4-20°C. Crystal-clear water, steep drop-offs.',
                'marine_life' => 'Pike, perch, eel, vendace (Fontane maräne — endemic).',
                'access_notes' => 'Neuglobsow, north of Berlin. Nature reserve — limited access points.',
            ],
            [
                'name' => 'Sundhäuser See',
                'country' => 'Germany',
                'region' => 'Thuringia',
                'latitude' => 51.4200,
                'longitude' => 10.9600,
                'max_depth' => 35,
                'water_type' => 'lake',
                'conditions' => 'Former gravel pit. Visibility 5-15m. Water temp 5-20°C. Submerged objects: airplane, bus, boat. Popular training site.',
                'marine_life' => 'Pike, perch, carp, catfish.',
                'access_notes' => 'Nordhausen, Thuringia. Well-organized dive site.',
                'facilities' => 'Dive center, fill station, changing rooms, camping.',
            ],
            [
                'name' => 'Kulkwitzer See — Leipzig',
                'country' => 'Germany',
                'region' => 'Saxony',
                'latitude' => 51.3300,
                'longitude' => 12.2800,
                'max_depth' => 30,
                'water_type' => 'lake',
                'conditions' => 'Former open-pit mine. Visibility 5-10m. Water temp 5-20°C. Submerged platforms, boat wreck.',
                'marine_life' => 'Pike, perch, carp, eel.',
                'access_notes' => 'West of Leipzig. Easy access, parking.',
                'facilities' => 'Dive center, fill station, beach, restaurant.',
            ],
            [
                'name' => 'Schieferbergwerk Nuttlar',
                'country' => 'Germany',
                'region' => 'North Rhine-Westphalia',
                'latitude' => 51.3100,
                'longitude' => 8.3700,
                'max_depth' => 25,
                'water_type' => 'quarry',
                'conditions' => 'Flooded slate mine in the Sauerland. Underground halls and corridors. Visibility 5-15m. Water temp 8-10°C year-round. Unique mine diving.',
                'marine_life' => 'None — underground mine.',
                'access_notes' => 'Nuttlar, Sauerland. Guided mine dives only — booking required.',
                'facilities' => 'Dive center, equipment rental, changing rooms.',
            ],
            [
                'name' => 'Schieferbergwerk Felicitas',
                'country' => 'Germany',
                'region' => 'North Rhine-Westphalia',
                'latitude' => 51.3000,
                'longitude' => 8.3500,
                'max_depth' => 20,
                'water_type' => 'quarry',
                'conditions' => 'Flooded slate mine. Huge underground halls with crystal-clear water. Visibility 10-20m. Water temp 8-10°C year-round.',
                'marine_life' => 'None — underground mine.',
                'access_notes' => 'Near Nuttlar, Sauerland. Guided mine dives — booking required.',
                'facilities' => 'Dive center, equipment rental.',
            ],
            [
                'name' => 'Messinghausen See',
                'country' => 'Germany',
                'region' => 'North Rhine-Westphalia',
                'latitude' => 51.4000,
                'longitude' => 8.5500,
                'max_depth' => 15,
                'water_type' => 'lake',
                'conditions' => 'Small lake in the Sauerland. Visibility 3-8m. Water temp 5-18°C. Good training site.',
                'marine_life' => 'Pike, perch, carp.',
                'access_notes' => 'Messinghausen, near Brilon. Club access.',
                'facilities' => 'Basic facilities, parking.',
            ],
            [
                'name' => 'Fühlinger See — Köln',
                'country' => 'Germany',
                'region' => 'North Rhine-Westphalia',
                'latitude' => 51.0200,
                'longitude' => 6.9300,
                'max_depth' => 15,
                'water_type' => 'lake',
                'conditions' => 'Urban lake complex north of Cologne. Visibility 3-8m. Water temp 5-20°C. Popular training site for Cologne/Bonn clubs.',
                'marine_life' => 'Pike, perch, carp, catfish.',
                'access_notes' => 'Köln-Chorweiler. Easy access, parking.',
                'facilities' => 'Regatta course, beach, parking.',
            ],
            [
                'name' => 'Blindsee — Biberwier',
                'country' => 'Germany',
                'region' => 'Tyrol (Austria border)',
                'latitude' => 47.3600,
                'longitude' => 10.8900,
                'max_depth' => 25,
                'water_type' => 'lake',
                'conditions' => 'Alpine lake near Fernpass. Visibility 10-20m (excellent). Water temp 4-18°C. Submerged forest, crystal-clear mountain water. Popular with German/Austrian clubs.',
                'marine_life' => 'Trout, char, crayfish.',
                'access_notes' => 'Biberwier, near Fernpass (Austrian side but popular with German clubs). Parking at the lake.',
                'facilities' => 'Parking, natural setting. No facilities on site.',
            ],
            // ── Batch 4 — Spain (10 new) ─────────────────────────
            [
                'name' => 'Illes Medes — Marine Reserve',
                'country' => 'Spain',
                'region' => 'Costa Brava, Catalonia',
                'latitude' => 42.0460,
                'longitude' => 3.2240,
                'max_depth' => 50,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Protected marine reserve since 1990. Visibility 10-25m. Water temp 13-25°C. 7 islands with caves, tunnels, walls. One of the best dives in the Med.',
                'marine_life' => 'Huge groupers, barracuda schools, eagle rays, moray eels, octopus, nudibranchs. Gorgonians, red coral.',
                'access_notes' => 'Boat from L\'Estartit (5min). Multiple dive centers.',
                'facilities' => 'Many dive centers, equipment rental, courses. Nitrox available.',
            ],
            [
                'name' => 'Cabo de Palos — Islas Hormigas',
                'country' => 'Spain',
                'region' => 'Murcia',
                'latitude' => 37.6300,
                'longitude' => -0.6800,
                'max_depth' => 50,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Marine reserve. Visibility 15-30m. Water temp 14-26°C. Volcanic pinnacles, walls. El Naranjito wreck. One of Spain\'s top dive areas.',
                'marine_life' => 'Eagle rays, barracuda, groupers, dentex, amberjack, sunfish (Mola mola). Gorgonians.',
                'access_notes' => 'Cabo de Palos, near La Manga del Mar Menor. Boat dives.',
                'facilities' => 'Dive centers, equipment rental, courses.',
            ],
            [
                'name' => 'Isla de Tabarca',
                'country' => 'Spain',
                'region' => 'Alicante, Valencia',
                'latitude' => 38.1650,
                'longitude' => -0.4800,
                'max_depth' => 30,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Marine reserve. Visibility 10-25m. Water temp 14-26°C. Spain\'s first marine reserve (1986). Posidonia meadows.',
                'marine_life' => 'Groupers, moray eels, octopus, barracuda, nudibranchs. Posidonia meadows.',
                'access_notes' => 'Boat from Santa Pola or Alicante. Dive centers on mainland.',
            ],
            [
                'name' => 'Tenerife — El Puertito',
                'country' => 'Spain',
                'region' => 'Canary Islands',
                'latitude' => 28.0900,
                'longitude' => -16.7800,
                'max_depth' => 20,
                'water_type' => 'sea',
                'conditions' => 'Atlantic/subtropical. Visibility 15-30m. Water temp 18-24°C year-round. Volcanic underwater landscapes. Famous for resident green turtles.',
                'marine_life' => 'Green turtles (resident), stingrays, angel sharks, barracuda, trumpetfish, moray eels.',
                'access_notes' => 'South Tenerife, near Adeje. Shore entry. Multiple dive centers.',
                'facilities' => 'Many dive centers, equipment rental, courses.',
            ],
            [
                'name' => 'Lanzarote — Museo Atlántico',
                'country' => 'Spain',
                'region' => 'Canary Islands',
                'latitude' => 28.9200,
                'longitude' => -13.6700,
                'max_depth' => 15,
                'water_type' => 'sea',
                'conditions' => 'Atlantic. Europe\'s first underwater sculpture museum by Jason deCaires Taylor. Visibility 15-30m. Water temp 18-23°C. 300+ sculptures at 12-15m.',
                'marine_life' => 'Angel sharks, stingrays, barracuda, octopus. Sculptures colonized by marine life.',
                'access_notes' => 'Playa Blanca, south Lanzarote. Boat dive. Booking required.',
                'facilities' => 'Dive centers, equipment rental.',
            ],
            [
                'name' => 'El Hierro — Mar de las Calmas',
                'country' => 'Spain',
                'region' => 'Canary Islands',
                'latitude' => 27.7200,
                'longitude' => -18.0100,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Atlantic. Visibility 20-40m. Water temp 19-25°C. Volcanic arches, caves, lava tunnels. UNESCO Biosphere Reserve. Calmest waters in the Canaries.',
                'marine_life' => 'Manta rays, whale sharks (rare), groupers, barracuda, turtles, angel sharks. Volcanic reef fish.',
                'access_notes' => 'La Restinga, south El Hierro. Small island — fly via Tenerife or ferry.',
                'facilities' => 'Dive centers, equipment rental.',
            ],
            [
                'name' => 'Gran Canaria — El Cabrón',
                'country' => 'Spain',
                'region' => 'Canary Islands',
                'latitude' => 27.8600,
                'longitude' => -15.3700,
                'max_depth' => 25,
                'water_type' => 'sea',
                'conditions' => 'Atlantic. Visibility 15-30m. Water temp 18-24°C. Marine reserve. Volcanic rock formations, caves, arches.',
                'marine_life' => 'Trumpetfish, parrotfish, angel sharks, stingrays, barracuda, octopus, nudibranchs.',
                'access_notes' => 'Arinaga, east Gran Canaria. Shore entry.',
                'facilities' => 'Dive centers nearby, equipment rental.',
            ],
            [
                'name' => 'Mallorca — Cala Ratjada',
                'country' => 'Spain',
                'region' => 'Balearic Islands',
                'latitude' => 39.7100,
                'longitude' => 3.4600,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 15-30m. Water temp 14-26°C. Caves (Cova del Drac), walls, wrecks.',
                'marine_life' => 'Groupers, barracuda, moray eels, octopus, nudibranchs. Posidonia meadows.',
                'access_notes' => 'Cala Ratjada, northeast Mallorca. Boat dives.',
                'facilities' => 'Dive centers, equipment rental, courses.',
            ],
            [
                'name' => 'Tarifa — Strait of Gibraltar',
                'country' => 'Spain',
                'region' => 'Cádiz, Andalusia',
                'latitude' => 36.0100,
                'longitude' => -5.6000,
                'max_depth' => 30,
                'water_type' => 'sea',
                'conditions' => 'Atlantic/Mediterranean junction. Visibility 5-15m. Water temp 15-22°C. Strong currents — advanced divers. Where Atlantic meets Mediterranean.',
                'marine_life' => 'Dolphins, orcas (seasonal), tuna, sunfish, groupers. Unique mix of Atlantic and Mediterranean species.',
                'access_notes' => 'Tarifa, southernmost point of continental Europe. Dive centers in town.',
                'facilities' => 'Dive centers, equipment rental.',
            ],
            [
                'name' => 'Formentera — La Mola',
                'country' => 'Spain',
                'region' => 'Balearic Islands',
                'latitude' => 38.6600,
                'longitude' => 1.5700,
                'max_depth' => 35,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 20-40m (some of the clearest in the Med). Water temp 14-26°C. Posidonia meadows (UNESCO). Caves, walls.',
                'marine_life' => 'Groupers, barracuda, moray eels, octopus. Pristine posidonia meadows.',
                'access_notes' => 'Formentera, ferry from Ibiza. Dive centers on the island.',
                'facilities' => 'Dive centers, equipment rental.',
            ],
            // ── Batch 4 — Italy (10 new, incl. Portofino) ────────
            [
                'name' => 'Portofino Marine Park',
                'country' => 'Italy',
                'region' => 'Liguria',
                'latitude' => 44.3000,
                'longitude' => 9.2100,
                'max_depth' => 50,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 15-30m. Water temp 14-25°C. Marine protected area. 20+ dive sites. Christ of the Abyss statue at 17m — iconic. Walls, caves, wrecks.',
                'marine_life' => 'Groupers, barracuda, moray eels, octopus, nudibranchs, seahorses. Red coral, gorgonians.',
                'access_notes' => 'Boat from Camogli, Santa Margherita Ligure, or Portofino. Dive permit required.',
                'facilities' => 'Dive centers, equipment rental, courses. Nitrox available.',
                'website_url' => 'https://portofinodivers.com',
            ],
            [
                'name' => 'Sardinia — Capo Caccia (Alghero)',
                'country' => 'Italy',
                'region' => 'Sardinia',
                'latitude' => 40.5700,
                'longitude' => 8.1600,
                'max_depth' => 45,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 20-40m. Water temp 14-25°C. Dramatic cliffs, caves (Grotta di Nereo — Europe\'s largest underwater cave), walls.',
                'marine_life' => 'Groupers, barracuda, lobsters, moray eels, red coral. Grotta di Nereo — spectacular.',
                'access_notes' => 'Boat from Alghero. Dive centers in Alghero.',
            ],
            [
                'name' => 'Sardinia — La Maddalena Archipelago',
                'country' => 'Italy',
                'region' => 'Sardinia',
                'latitude' => 41.2100,
                'longitude' => 9.4100,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. National park. Visibility 20-40m. Water temp 14-25°C. Granite formations, white sand, turquoise water.',
                'marine_life' => 'Groupers, octopus, moray eels, barracuda, nudibranchs. Posidonia meadows.',
                'access_notes' => 'Boat from Palau or La Maddalena. Dive centers on both.',
            ],
            [
                'name' => 'Isole Tremiti',
                'country' => 'Italy',
                'region' => 'Puglia, Adriatic',
                'latitude' => 42.1200,
                'longitude' => 15.5100,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Adriatic. Marine reserve. Visibility 15-30m. Water temp 14-25°C. Caves, walls, wrecks. Remote and pristine.',
                'marine_life' => 'Groupers, barracuda, lobsters, moray eels, nudibranchs. Gorgonians.',
                'access_notes' => 'Ferry from Termoli or helicopter from Foggia. Dive centers on San Domino island.',
            ],
            [
                'name' => 'Isola d\'Elba',
                'country' => 'Italy',
                'region' => 'Tuscany',
                'latitude' => 42.7700,
                'longitude' => 10.2500,
                'max_depth' => 45,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean/Tyrrhenian. Visibility 15-30m. Water temp 14-25°C. Wrecks (Elviscot at 12m), walls, caves. Part of Tuscan Archipelago National Park.',
                'marine_life' => 'Groupers, barracuda, moray eels, octopus, dolphins (seasonal). Gorgonians, red coral.',
                'access_notes' => 'Ferry from Piombino. Dive centers in Portoferraio, Marina di Campo.',
            ],
            [
                'name' => 'Capo Noli',
                'country' => 'Italy',
                'region' => 'Liguria',
                'latitude' => 44.2000,
                'longitude' => 8.4200,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 15-25m. Water temp 14-25°C. Dramatic walls dropping from shore. Caves, overhangs.',
                'marine_life' => 'Groupers, moray eels, octopus, nudibranchs. Gorgonians, sponges.',
                'access_notes' => 'Noli, Liguria. Shore and boat dives. Dive centers in Noli and Spotorno.',
            ],
            [
                'name' => 'Ischia — Castello Aragonese',
                'country' => 'Italy',
                'region' => 'Campania',
                'latitude' => 40.7300,
                'longitude' => 13.9600,
                'max_depth' => 30,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 10-25m. Water temp 14-26°C. Volcanic CO2 vents create unique acidified zone — studied by marine scientists. Thermal springs.',
                'marine_life' => 'Unique ecosystem adapted to acidification. Posidonia, nudibranchs, octopus.',
                'access_notes' => 'Ferry from Naples to Ischia. Dive centers on the island.',
            ],
            [
                'name' => 'Pantelleria',
                'country' => 'Italy',
                'region' => 'Sicily',
                'latitude' => 36.7800,
                'longitude' => 11.9900,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 20-40m. Water temp 16-27°C. Volcanic island between Sicily and Tunisia. Lava formations, arches, caves.',
                'marine_life' => 'Groupers, barracuda, amberjack, tuna, lobsters. Volcanic reef formations.',
                'access_notes' => 'Fly from Palermo/Trapani or ferry from Trapani. Dive centers on island.',
            ],
            [
                'name' => 'Nervi — Genova',
                'country' => 'Italy',
                'region' => 'Liguria',
                'latitude' => 44.3800,
                'longitude' => 8.9900,
                'max_depth' => 30,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 10-20m. Water temp 14-25°C. Rocky coast east of Genoa. Easy shore dives, walls.',
                'marine_life' => 'Octopus, moray eels, nudibranchs, scorpionfish. Gorgonians.',
                'access_notes' => 'Nervi, eastern suburb of Genoa. Shore entry from the promenade.',
                'facilities' => 'Dive centers in Genoa area.',
            ],
            [
                'name' => 'Capri — Faraglioni',
                'country' => 'Italy',
                'region' => 'Campania',
                'latitude' => 40.5400,
                'longitude' => 14.2500,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Mediterranean. Visibility 15-30m. Water temp 14-26°C. Iconic rock formations. Caves, arches, walls. Blue Grotto area.',
                'marine_life' => 'Groupers, barracuda, moray eels, octopus, nudibranchs. Gorgonians.',
                'access_notes' => 'Boat from Naples, Sorrento, or Positano. Dive centers on Capri.',
            ],
            // ── Batch 4 — Portugal (6 new) ───────────────────────
            [
                'name' => 'Azores — São Miguel (Vila Franca)',
                'country' => 'Portugal',
                'region' => 'Azores, Atlantic',
                'latitude' => 37.7100,
                'longitude' => -25.4300,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Atlantic. Visibility 15-40m. Water temp 17-24°C. Volcanic formations, seamounts. Blue sharks, mantas, whale sharks (seasonal). World-class pelagic diving.',
                'marine_life' => 'Blue sharks, mako sharks, manta rays, whale sharks, mobula rays, sperm whales. Volcanic reef fish.',
                'access_notes' => 'Fly to Ponta Delgada (PDL). Dive centers in Vila Franca do Campo.',
                'facilities' => 'Dive centers, equipment rental, courses. Shark diving trips.',
            ],
            [
                'name' => 'Azores — Faial (Princess Alice Bank)',
                'country' => 'Portugal',
                'region' => 'Azores, Atlantic',
                'latitude' => 37.8500,
                'longitude' => -29.0000,
                'max_depth' => 35,
                'water_type' => 'sea',
                'conditions' => 'Atlantic. Open ocean seamount 80km south of Faial. Visibility 20-40m. Water temp 18-24°C. One of the world\'s best manta ray sites. Liveaboard or long boat ride.',
                'marine_life' => 'Manta rays (huge aggregations), mobula rays, blue sharks, whale sharks, tuna, dolphins.',
                'access_notes' => 'Boat from Horta, Faial island. Long boat ride — weather dependent.',
            ],
            [
                'name' => 'Algarve — Portimão Wrecks',
                'country' => 'Portugal',
                'region' => 'Algarve',
                'latitude' => 37.1000,
                'longitude' => -8.5300,
                'max_depth' => 30,
                'water_type' => 'sea',
                'conditions' => 'Atlantic. Visibility 8-20m. Water temp 15-23°C. Artificial reef of 4 deliberately sunk ships (Ocean Revival project). Unique wreck diving.',
                'marine_life' => 'Groupers, moray eels, octopus, nudibranchs, seahorses. Wrecks colonized by marine life.',
                'access_notes' => 'Boat from Portimão marina. Dive centers in Portimão and Lagos.',
                'facilities' => 'Dive centers, equipment rental, courses.',
            ],
            [
                'name' => 'Arrábida Marine Park',
                'country' => 'Portugal',
                'region' => 'Setúbal',
                'latitude' => 38.4700,
                'longitude' => -8.9700,
                'max_depth' => 30,
                'water_type' => 'sea',
                'conditions' => 'Atlantic. Marine park (Prof. Luiz Saldanha). Visibility 8-20m. Water temp 14-22°C. Rocky reefs, caves, kelp forests.',
                'marine_life' => 'Octopus, seahorses, nudibranchs, conger eels, sunfish (Mola mola). Kelp forests.',
                'access_notes' => 'Boat from Sesimbra. Dive permit required from park authority.',
            ],
            [
                'name' => 'Madeira — Garajau Marine Reserve',
                'country' => 'Portugal',
                'region' => 'Madeira, Atlantic',
                'latitude' => 32.6300,
                'longitude' => -16.8500,
                'max_depth' => 40,
                'water_type' => 'sea',
                'conditions' => 'Atlantic. Visibility 15-30m. Water temp 18-24°C. Volcanic formations, caves. Marine reserve since 1986. Huge groupers.',
                'marine_life' => 'Giant groupers (very approachable), barracuda, manta rays, turtles, moray eels.',
                'access_notes' => 'Fly to Funchal. Dive centers in Funchal and Caniço.',
                'facilities' => 'Dive centers, equipment rental, courses.',
            ],
            [
                'name' => 'Sagres — Cabo de São Vicente',
                'country' => 'Portugal',
                'region' => 'Algarve',
                'latitude' => 37.0000,
                'longitude' => -8.9900,
                'max_depth' => 30,
                'water_type' => 'sea',
                'conditions' => 'Atlantic. Visibility 8-20m. Water temp 14-22°C. Southwestern tip of Europe. Strong currents — advanced divers. Rocky reefs, caves.',
                'marine_life' => 'Groupers, moray eels, octopus, barracuda, sunfish. Kelp forests.',
                'access_notes' => 'Sagres, western Algarve. Dive centers in Sagres.',
                'facilities' => 'Dive centers, equipment rental.',
            ],
            // ── Batch 4 — Netherlands (8 new) ────────────────────
            [
                'name' => 'Grevelingenmeer — Den Osse',
                'country' => 'Netherlands',
                'region' => 'Zeeland',
                'latitude' => 51.7400,
                'longitude' => 3.8600,
                'max_depth' => 25,
                'water_type' => 'sea',
                'conditions' => 'Saltwater lake. Visibility 3-10m. Water temp 5-20°C. Rich biotopes on old concrete slabs. Eels, pouting, anemones.',
                'marine_life' => 'Eels, pouting, anemones, nudibranchs, crabs, lobsters.',
                'access_notes' => 'Den Osse, Nieuwe Kerkweg. Shore entry from jetty.',
                'facilities' => 'Parking, easy access.',
            ],
            [
                'name' => 'Grevelingenmeer — Le Serpent',
                'country' => 'Netherlands',
                'region' => 'Zeeland',
                'latitude' => 51.7500,
                'longitude' => 3.8400,
                'max_depth' => 20,
                'water_type' => 'sea',
                'conditions' => 'Saltwater lake. Visibility 3-10m. Water temp 5-20°C. Named after a serpentine underwater ridge.',
                'marine_life' => 'Anemones, nudibranchs, crabs, lobsters, seahorses.',
                'access_notes' => 'Grevelingenmeer, Zeeland. Shore entry.',
            ],
            [
                'name' => 'Oosterschelde — Zeelandbrug',
                'country' => 'Netherlands',
                'region' => 'Zeeland',
                'latitude' => 51.6300,
                'longitude' => 3.9100,
                'max_depth' => 25,
                'water_type' => 'sea',
                'conditions' => 'Tidal estuary. Visibility 3-10m. Water temp 5-18°C. Strong tidal currents — dive at slack water. Famous for cuttlefish mating (May-Jun). One of the most biodiverse sites in the world.',
                'marine_life' => 'Cuttlefish, seahorses, lobsters, anemones, nudibranchs, crabs, starfish.',
                'access_notes' => 'Near Zierikzee. Tide tables essential. Shore entry from bridge pillars.',
                'facilities' => 'Parking. Dive shops in Renesse and Zierikzee.',
            ],
            [
                'name' => 'Oosterschelde — Burghsluis',
                'country' => 'Netherlands',
                'region' => 'Zeeland',
                'latitude' => 51.6800,
                'longitude' => 3.7500,
                'max_depth' => 15,
                'water_type' => 'sea',
                'conditions' => 'Tidal estuary. Visibility 3-8m. Water temp 5-18°C. Sheltered bay — easier currents than Zeelandbrug.',
                'marine_life' => 'Cuttlefish, seahorses, crabs, lobsters, anemones.',
                'access_notes' => 'Burghsluis, Schouwen-Duiveland. Shore entry.',
                'facilities' => 'Parking, easy access.',
            ],
            [
                'name' => 'Vinkeveense Plassen — Zandeiland 4',
                'country' => 'Netherlands',
                'region' => 'Utrecht',
                'latitude' => 52.2200,
                'longitude' => 4.9400,
                'max_depth' => 30,
                'water_type' => 'lake',
                'conditions' => 'Freshwater lake. Visibility 3-8m. Water temp 5-20°C. Famous submerged full-sized bus, boat, and other objects. Netherlands\' most famous inland dive site.',
                'marine_life' => 'Pike, perch, carp, eel, crayfish.',
                'access_notes' => 'Vinkeveen, south of Amsterdam. Entry fee. Parking.',
                'facilities' => 'Dive center, fill station, changing rooms, restaurant.',
            ],
            [
                'name' => 'De Groene Heuvels — Nijmegen',
                'country' => 'Netherlands',
                'region' => 'Gelderland',
                'latitude' => 51.8400,
                'longitude' => 5.7800,
                'max_depth' => 28,
                'water_type' => 'lake',
                'conditions' => 'Freshwater lake west of Nijmegen. Visibility 3-8m. Water temp 5-20°C. Several sunken objects. Good for beginners and advanced.',
                'marine_life' => 'Pike, perch, carp, eel.',
                'access_notes' => 'West of Nijmegen on the A50. Parking, easy access.',
                'facilities' => 'Parking, entry facilities.',
            ],
            [
                'name' => 'Noordzee — Scheveningen Wrecks',
                'country' => 'Netherlands',
                'region' => 'South Holland',
                'latitude' => 52.1100,
                'longitude' => 4.2600,
                'max_depth' => 25,
                'water_type' => 'sea',
                'conditions' => 'North Sea. Visibility 2-8m. Water temp 6-18°C. WWII wrecks, fishing vessels. Strong currents — advanced divers. Cold water.',
                'marine_life' => 'Lobsters, crabs, cod, pollack, wrasse. Wreck-encrusted marine life.',
                'access_notes' => 'Boat from Scheveningen harbour. Dive operators required.',
                'facilities' => 'Dive centers in The Hague/Scheveningen.',
            ],
            [
                'name' => 'Toolenburgerplas — Hoofddorp',
                'country' => 'Netherlands',
                'region' => 'North Holland',
                'latitude' => 52.2900,
                'longitude' => 4.6700,
                'max_depth' => 10,
                'water_type' => 'lake',
                'conditions' => 'Freshwater lake near Schiphol. Visibility 2-5m. Water temp 5-20°C. Shallow — good for training. Submerged objects.',
                'marine_life' => 'Pike, eel, carp, perch, crayfish, catfish.',
                'access_notes' => 'Hoofddorp, Haarlemmermeer. Free access.',
                'facilities' => 'Parking, beach area.',
            ],
            // ── Batch 5 ──────────────────────────────────────────
            [
                'name' => 'EDP Art Reef by Vhils — Albufeira',
                'country' => 'Portugal',
                'region' => 'Algarve',
                'latitude' => 37.0800,
                'longitude' => -8.2500,
                'max_depth' => 12,
                'water_type' => 'sea',
                'conditions' => 'Atlantic. Visibility 8-20m. Water temp 15-23°C. Portugal\'s first underwater museum — 13 sculptures by street artist Vhils (Alexandre Farto), made from decommissioned power plant parts. Artificial reef ~1 mile offshore.',
                'marine_life' => 'Sculptures colonizing with marine life. Octopus, nudibranchs, sea bream, wrasse.',
                'access_notes' => 'Boat from Albufeira marina. Dive centers in Albufeira. Divers only (12m depth).',
                'facilities' => 'Dive centers, equipment rental.',
            ],
            [
                'name' => 'Airbus A300 Wreck — Kuşadası',
                'country' => 'Turkey',
                'region' => 'Aydın, Aegean Sea',
                'latitude' => 37.8600,
                'longitude' => 27.2600,
                'max_depth' => 24,
                'water_type' => 'sea',
                'conditions' => 'Aegean Sea. Visibility 10-25m. Water temp 16-26°C. World\'s largest deliberately sunk aircraft (54m long, 44m wingspan). Sunk June 2016 as artificial reef. Fuselage intact, now coral-encrusted.',
                'marine_life' => 'Fish schools inside fuselage, groupers, octopus, moray eels. Rapidly colonizing reef.',
                'access_notes' => 'Boat from Kuşadası harbour. Multiple dive centers.',
                'facilities' => 'Dive centers, equipment rental, courses.',
            ],
            [
                'name' => 'Salem Express Wreck',
                'country' => 'Egypt',
                'region' => 'Red Sea, Safaga',
                'latitude' => 26.6503,
                'longitude' => 34.0633,
                'max_depth' => 32,
                'water_type' => 'sea',
                'conditions' => 'Red Sea. Visibility 15-30m. Water temp 22-28°C. 115m passenger ferry sunk Dec 1991 at Hyndman Reef with massive loss of life. Lies on port side. Bow at 32m, propeller at 14m. Controversial but iconic wreck dive.',
                'marine_life' => 'Coral growth on hull, lionfish, groupers, glassfish inside. Lifeboats on seabed.',
                'access_notes' => 'Day trip from Safaga or Hurghada. Liveaboard routes. AOWD required.',
                'safety_notes' => 'War grave — do not enter or disturb. Respect the site.',
            ],
            [
                'name' => 'River Gurara Wreck — Sesimbra',
                'country' => 'Portugal',
                'region' => 'Setúbal',
                'latitude' => 38.4200,
                'longitude' => -9.2200,
                'max_depth' => 30,
                'water_type' => 'sea',
                'conditions' => 'Atlantic. Visibility 8-15m. Water temp 14-22°C. 170m Nigerian cargo ship sunk Feb 1989 at Cape Espichel. Most popular wreck in Sesimbra. Stern at 25m, bow at 30m. Two dive sites (bow & stern).',
                'marine_life' => 'Conger eels, moray eels, octopus, nudibranchs, schools of fish. Gorgonians on hull.',
                'access_notes' => 'Boat from Sesimbra. All local dive centers visit this wreck.',
            ],
            [
                'name' => 'Nemo Reef',
                'country' => 'Egypt',
                'region' => 'Red Sea',
                'latitude' => 27.2000,
                'longitude' => 33.8700,
                'max_depth' => 18,
                'water_type' => 'sea',
                'conditions' => 'Red Sea. Visibility 15-30m. Water temp 22-28°C. Shallow coral reef, good for all levels.',
                'marine_life' => 'Clownfish, lionfish, moray eels, butterflyfish, parrotfish. Healthy hard and soft corals.',
                'access_notes' => 'Boat from Hurghada. Day trip.',
            ],
        ];

        foreach ($sites as $site) {
            DiveSite::updateOrCreate(
                ['name' => $site['name']],
                array_merge($site, ['is_active' => true]),
            );
        }
    }
}
