<?php

namespace Database\Seeders;

use App\Models\DiveSite;
use Illuminate\Database\Seeder;

class DiveSiteSeeder extends Seeder
{
    public function run(): void
    {
        $sites = [
            // === LUXEMBOURG ===
            [
                'name' => 'Lac de la Haute-Sûre — Lultzhausen',
                'country' => 'Luxembourg',
                'region' => 'Haute-Sûre',
                'latitude' => 49.9049,
                'longitude' => 5.8822,
                'max_depth' => 33,
                'water_type' => 'lake',
                'conditions' => 'Freshwater reservoir. Visibility 3-8m depending on season, best in autumn/winter. Thermocline around 10-15m in summer. Water temp 4-22°C.',
                'marine_life' => 'Pike, perch, carp, trout, crayfish. Submerged trees and structures create interesting underwater landscapes.',
                'safety_notes' => 'Bring own safety equipment: O2 kit, surface marker buoys. No permanent rescue station. Strong currents possible near dam.',
                'access_notes' => 'Multiple entry points between Lultzhausen, Insenborn and Liefrange. Parking at each entry. Air fills at Lultzhausen youth hostel (€0.50 coin operated) or Hôtel Peiffer in Insenborn.',
                'facilities' => 'Parking, air fills nearby, restaurants in villages, youth hostel accommodation in Lultzhausen.',
                'nearest_hospital' => 'Centre Hospitalier Emile Mayrisch (CHEM), Rue Emile Mayrisch, 4240 Esch-sur-Alzette. Tel: +352 5711 1. Hyperbaric chamber: 6 seated / 3 lying.',
                'website_url' => 'https://www.visitluxembourg.com',
                'is_active' => true,
            ],
            [
                'name' => 'Lac de la Haute-Sûre — Insenborn',
                'country' => 'Luxembourg',
                'region' => 'Haute-Sûre',
                'latitude' => 49.9120,
                'longitude' => 5.8950,
                'max_depth' => 28,
                'water_type' => 'lake',
                'conditions' => 'Sheltered bay, calmer than Lultzhausen. Visibility 3-6m. Good for training dives. Muddy bottom in shallows.',
                'marine_life' => 'Pike, perch, small fish schools. Submerged tree stumps from before the dam was built.',
                'safety_notes' => 'Shallow entry, suitable for beginners. Watch for boat traffic in summer months.',
                'access_notes' => 'Entry from Insenborn beach area. Parking available. Air fills at Hôtel Peiffer.',
                'facilities' => 'Parking, beach area, Hôtel Peiffer with air fills and accommodation.',
                'nearest_hospital' => 'CHEM Esch-sur-Alzette. Tel: +352 5711 1.',
                'is_active' => true,
            ],

            // === BELGIUM — Quarries ===
            [
                'name' => 'Carrière de Barges',
                'country' => 'Belgium',
                'region' => 'Hainaut',
                'latitude' => 50.5911,
                'longitude' => 3.3948,
                'max_depth' => 50,
                'water_type' => 'quarry',
                'conditions' => 'Deep quarry with multiple depth levels. Visibility 3-10m. Cold below thermocline. Suitable for deep diving training.',
                'marine_life' => 'Pike, perch, carp. Submerged objects including a car and platforms at various depths.',
                'safety_notes' => 'Deep site — safety team with O2 and reserve tank required. Decompression diving possible. Cold water below 15m year-round.',
                'access_notes' => 'Rue du Pont à Rieu, 7500 Tournai. Managed by Association Tournaisienne de Plongée. Reservation recommended.',
                'facilities' => 'Changing rooms, O2 kit, defibrillator on site.',
                'nearest_hospital' => 'CHRU de Lille — Hôpital Roger Salengro, Avenue Oscar Lambert 2, 59037 Lille Cedex, France. Tel: +33 3 20 44 55 50. Hyperbaric chamber.',
                'website_url' => 'http://www.aquasubtournai.net',
                'is_active' => true,
            ],
            [
                'name' => 'Carrière de Vodelée',
                'country' => 'Belgium',
                'region' => 'Namur',
                'latitude' => 50.1847,
                'longitude' => 4.6539,
                'max_depth' => 40,
                'water_type' => 'quarry',
                'conditions' => 'Popular training quarry. Visibility 3-8m. Multiple platforms at 5m, 10m, 20m for exercises. Water temp 6-20°C.',
                'marine_life' => 'Pike, perch, roach. Submerged boat, car, and training platforms.',
                'safety_notes' => 'Well-organized site with marked depth zones. O2 available on site. Good for all levels.',
                'access_notes' => 'Rue de la Carrière, 5575 Vodelée (Doische). Open weekends and holidays March-November. Reservation required for clubs.',
                'facilities' => 'Changing rooms, hot showers, air fills, O2, parking, picnic area, toilets.',
                'nearest_hospital' => 'CHU UCL Namur — Site Dinant, Rue Saint-Jacques 501, 5500 Dinant. Tel: +32 82 21 21 11.',
                'is_active' => true,
            ],
            [
                'name' => 'Carrière de Floreffe',
                'country' => 'Belgium',
                'region' => 'Namur',
                'latitude' => 50.4347,
                'longitude' => 4.7597,
                'max_depth' => 30,
                'water_type' => 'quarry',
                'conditions' => 'Medium-depth quarry ideal for training. Visibility 2-6m. Algae bloom possible in summer. Thermocline around 8-12m.',
                'marine_life' => 'Perch, roach, pike. Submerged platforms and training structures.',
                'safety_notes' => 'Suitable for beginners and intermediate divers. Slippery entry in wet weather.',
                'access_notes' => 'Rue de la Carrière, 5150 Floreffe. Open weekends April-October.',
                'facilities' => 'Changing rooms, parking, basic facilities.',
                'nearest_hospital' => 'CHU UCL Namur — Site Godinne, Avenue Docteur G. Thérasse 1, 5530 Yvoir. Tel: +32 81 42 21 11.',
                'is_active' => true,
            ],
            [
                'name' => 'Carrière de Rochefontaine',
                'country' => 'Belgium',
                'region' => 'Namur',
                'latitude' => 50.1200,
                'longitude' => 4.8100,
                'max_depth' => 35,
                'water_type' => 'quarry',
                'conditions' => 'Scenic quarry surrounded by forest. Visibility 4-10m, often better than other Belgian quarries. Cool water year-round.',
                'marine_life' => 'Pike, perch, trout. Rich aquatic vegetation in shallows.',
                'safety_notes' => 'Steep banks in places. Bring own safety equipment.',
                'access_notes' => 'Rue de Roche Fontaine, 5570 Beauraing. Club reservation required.',
                'facilities' => 'Parking, basic changing area.',
                'nearest_hospital' => 'CHU UCL Namur — Site Dinant. Tel: +32 82 21 21 11.',
                'is_active' => true,
            ],
            [
                'name' => 'Carrière de Dongelberg',
                'country' => 'Belgium',
                'region' => 'Brabant wallon',
                'latitude' => 50.7100,
                'longitude' => 4.9200,
                'max_depth' => 15,
                'water_type' => 'quarry',
                'conditions' => 'Shallow quarry, excellent for beginners and pool-alternative training. Visibility 2-5m. Warm in summer.',
                'marine_life' => 'Small fish, frogs, newts. Aquatic plants.',
                'safety_notes' => 'Very shallow — no deep diving risks. Watch for algae on entry rocks.',
                'access_notes' => 'Rue de la Carrière, 1370 Dongelberg (Jodoigne). Easy access.',
                'facilities' => 'Parking, basic facilities.',
                'nearest_hospital' => 'Clinique Saint-Pierre Ottignies, Avenue Reine Fabiola 9, 1340 Ottignies. Tel: +32 10 43 72 11.',
                'is_active' => true,
            ],

            // === BELGIUM — Indoor ===
            [
                'name' => 'Nemo 33',
                'country' => 'Belgium',
                'region' => 'Brussels',
                'latitude' => 50.8148,
                'longitude' => 4.3578,
                'max_depth' => 35,
                'water_type' => 'pool',
                'conditions' => 'Indoor diving pool. Non-chlorinated spring water at 30°C. Excellent visibility (15m+). Simulated caves at 10m depth. Open year-round.',
                'marine_life' => 'None — indoor pool. Underwater windows for spectators.',
                'safety_notes' => 'Controlled environment. Staff on site. Ideal for training and try-dives. Certification required for deep zone.',
                'access_notes' => 'Rue de Stalle 333, 1180 Uccle, Brussels. Metro: Stalle. Reservation required.',
                'facilities' => 'Changing rooms, showers, restaurant/bar, equipment rental, air fills, underwater windows, conference room.',
                'nearest_hospital' => 'Hôpital Erasme, Route de Lennik 808, 1070 Anderlecht. Tel: +32 2 555 31 11.',
                'website_url' => 'https://www.nemo33.com',
                'is_active' => true,
            ],
            [
                'name' => 'TODI',
                'country' => 'Belgium',
                'region' => 'Limburg',
                'latitude' => 51.0497,
                'longitude' => 5.2264,
                'max_depth' => 10,
                'water_type' => 'pool',
                'conditions' => 'Indoor tropical diving experience. Heated water at 30°C. Crystal clear visibility. Tropical fish and coral reef simulation.',
                'marine_life' => 'Tropical fish: clownfish, tangs, angelfish, rays. Living coral reef environment.',
                'safety_notes' => 'Controlled environment. Maximum depth 10m. Suitable for all levels including try-dives.',
                'access_notes' => 'Stationsstraat 146, 3580 Beringen. Easy highway access. Reservation required.',
                'facilities' => 'Changing rooms, showers, restaurant, equipment rental, shop, parking.',
                'nearest_hospital' => 'Jessa Ziekenhuis, Stadsomvaart 11, 3500 Hasselt. Tel: +32 11 30 81 11.',
                'website_url' => 'https://www.tyvol.be',
                'is_active' => true,
            ],

            // === ZEELAND (Netherlands) ===
            [
                'name' => 'Grevelingenmeer — Dreischor',
                'country' => 'Netherlands',
                'region' => 'Zeeland',
                'latitude' => 51.7350,
                'longitude' => 3.8650,
                'max_depth' => 25,
                'water_type' => 'sea',
                'conditions' => 'Saltwater lake (former estuary). Visibility 3-10m, best in winter. Tidal influence minimal. Water temp 4-20°C. Rich marine life.',
                'marine_life' => 'Lobsters, crabs, sea anemones, nudibranchs, flatfish, gobies, seahorses (rare), cuttlefish in spring. Excellent macro photography.',
                'safety_notes' => 'Shore diving. Watch for fishing lines. Some sites have strong currents near sluices. Dutch diving regulations apply.',
                'access_notes' => 'Dreischor entry point, Zeeland. Multiple parking areas along the lake. Air fills at local dive shops in Scharendijke.',
                'facilities' => 'Parking, dive shops in Scharendijke and Brouwershaven, restaurants.',
                'nearest_hospital' => 'Admiraal De Ruyter Ziekenhuis, \'s-Gravenpolderseweg 114, 4462 RA Goes. Tel: +31 113 23 40 00.',
                'website_url' => 'https://www.vvvzeeland.nl',
                'is_active' => true,
            ],
            [
                'name' => 'Grevelingenmeer — Scharendijke',
                'country' => 'Netherlands',
                'region' => 'Zeeland',
                'latitude' => 51.7420,
                'longitude' => 3.8530,
                'max_depth' => 20,
                'water_type' => 'sea',
                'conditions' => 'Popular shore dive site. Visibility 2-8m. Easy entry from jetty. Good for night dives. Sheltered from wind.',
                'marine_life' => 'Lobsters, crabs, shrimp, flatfish, gobies, sea anemones, nudibranchs, cuttlefish (spring). Excellent for macro.',
                'safety_notes' => 'Easy shore entry. Suitable for all levels. Watch for boat traffic near harbour.',
                'access_notes' => 'Scharendijke harbour, Zeeland. Large parking area. Multiple dive shops with air fills and equipment rental.',
                'facilities' => 'Dive shops, air fills, equipment rental, parking, restaurants, toilets.',
                'nearest_hospital' => 'Admiraal De Ruyter Ziekenhuis, Goes. Tel: +31 113 23 40 00.',
                'is_active' => true,
            ],
            [
                'name' => 'Oosterschelde — Wemeldinge',
                'country' => 'Netherlands',
                'region' => 'Zeeland',
                'latitude' => 51.5200,
                'longitude' => 3.9900,
                'max_depth' => 30,
                'water_type' => 'sea',
                'conditions' => 'Tidal estuary — MUST check tide tables. Dive only at slack water. Visibility 1-6m. Strong currents outside slack. Cold water in winter.',
                'marine_life' => 'Lobsters, crabs, sea anemones, sponges, nudibranchs, cuttlefish, seals (occasional). Very rich biodiversity.',
                'safety_notes' => 'TIDAL SITE — only dive at slack water. Check tide tables before every dive. Strong currents can be dangerous. Experienced divers recommended.',
                'access_notes' => 'Wemeldinge harbour, Zeeland. Parking at harbour. Check NOB dive site guide for exact entry points.',
                'facilities' => 'Parking, harbour facilities, restaurants in village.',
                'nearest_hospital' => 'Admiraal De Ruyter Ziekenhuis, Goes. Tel: +31 113 23 40 00.',
                'is_active' => true,
            ],

            // === FRANCE ===
            [
                'name' => 'Gravière du Fort',
                'country' => 'France',
                'region' => 'Alsace',
                'latitude' => 48.5567,
                'longitude' => 7.6450,
                'max_depth' => 15,
                'water_type' => 'quarry',
                'conditions' => 'Freshwater gravel pit near Strasbourg. Visibility 3-8m. Warm in summer (up to 24°C), cold in winter. Ideal for training and beginners.',
                'marine_life' => 'Pike, perch, carp, tench, roach. Aquatic plants and freshwater mussels.',
                'safety_notes' => 'Shallow site, very safe for beginners. No deep diving risks. Managed by FROG (Fédération Régionale pour l\'Organisation de la Gravière).',
                'access_notes' => '2 Impasse de la Gravière, 67810 Holtzheim. 10 min from Strasbourg centre. Easy parking.',
                'facilities' => 'Parking, changing area, picnic tables. Air fills at local dive shops in Strasbourg.',
                'nearest_hospital' => 'Hôpitaux Universitaires de Strasbourg — Nouvel Hôpital Civil, 1 Place de l\'Hôpital, 67000 Strasbourg. Tel: +33 3 88 11 67 68.',
                'website_url' => 'https://www.visit.alsace/237000360-la-graviere-du-fort/',
                'is_active' => true,
            ],
        ];

        foreach ($sites as $site) {
            DiveSite::updateOrCreate(['name' => $site['name']], $site);
        }
    }
}
