sonar.projectKey=collaed_divingclub
sonar.organization=collaed
sonar.projectName=divingclub

sonar.sources=app,config,database,resources,routes
sonar.tests=tests
sonar.exclusions=vendor/**,node_modules/**,public/build/**,storage/**,bootstrap/cache/**

sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=test-results.xml
